<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Daml.Runtime\Daml.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\wire-samples\data\*.json" LinkBase="wire-samples\data" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
