// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.TransferEventsV2;

/// <summary>
/// Generated from Daml record EventLog_HoldingsChangeResult
/// </summary>
public sealed record EventLog_HoldingsChangeResult : IDamlRecord<EventLog_HoldingsChangeResult>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create();

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static EventLog_HoldingsChangeResult FromRecord(DamlRecord record) => new EventLog_HoldingsChangeResult();

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create();
    }

}
