// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record AllocationView
/// </summary>
public sealed record AllocationView([property: DamlFieldAttribute("originalAllocationCid")] ContractId<IAllocation>? OriginalAllocationCid, [property: DamlFieldAttribute("settlement")] SettlementInfo Settlement, [property: DamlFieldAttribute("allocation")] AllocationSpecification Allocation, [property: DamlFieldAttribute("holdingCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> HoldingCids, [property: DamlFieldAttribute("createdAt")] DateTimeOffset CreatedAt, [property: DamlFieldAttribute("numIterations")] long NumIterations, [property: DamlFieldAttribute("expiresAt")] DateTimeOffset? ExpiresAt, [property: DamlFieldAttribute("availableActions")] IReadOnlyDictionary<AllocationAction, IReadOnlyList<IReadOnlyList<Party>>> AvailableActions, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("originalAllocationCid", OriginalAllocationCid is { } __OriginalAllocationCid ? new DamlOptional(__OriginalAllocationCid.ToDamlValue()) : DamlOptional.None),
        DamlField.Create("settlement", Settlement.ToRecord()),
        DamlField.Create("allocation", Allocation.ToRecord()),
        DamlField.Create("holdingCids", new DamlList(HoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("createdAt", new DamlTimestamp(CreatedAt)),
        DamlField.Create("numIterations", new DamlInt64(NumIterations)),
        DamlField.Create("expiresAt", ExpiresAt is { } __ExpiresAt ? new DamlOptional(new DamlTimestamp(__ExpiresAt)) : DamlOptional.None),
        DamlField.Create("availableActions", new DamlGenMap(AvailableActions.Select(kv => ((DamlValue)kv.Key.ToVariant(), (DamlValue)new DamlList(kv.Value.Select(x => (DamlValue)new DamlList(x.Select(x => (DamlValue)x.ToDamlValue()).ToList())).ToList()))).ToList())),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationView FromRecord(DamlRecord record) => new AllocationView(
        OriginalAllocationCid: record.GetRequiredField("originalAllocationCid").AsOptional().HasValue ? new ContractId<IAllocation>(record.GetRequiredField("originalAllocationCid").AsOptional().Value!.As<DamlContractId>().Value) : null,
        Settlement: SettlementInfo.FromRecord(record.GetRequiredField("settlement").As<DamlRecord>()),
        Allocation: AllocationSpecification.FromRecord(record.GetRequiredField("allocation").As<DamlRecord>()),
        HoldingCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("holdingCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        CreatedAt: record.GetRequiredField("createdAt").As<DamlTimestamp>().Value,
        NumIterations: record.GetRequiredField("numIterations").As<DamlInt64>().Value,
        ExpiresAt: record.GetRequiredField("expiresAt").AsOptional().HasValue ? record.GetRequiredField("expiresAt").AsOptional().Value!.As<DamlTimestamp>().Value : null,
        AvailableActions: (IReadOnlyDictionary<AllocationAction, IReadOnlyList<IReadOnlyList<Party>>>)record.GetRequiredField("availableActions").As<DamlGenMap>().Entries.ToDictionary(kv => AllocationAction.FromVariant(kv.Key.As<DamlVariant>()), kv => (IReadOnlyList<IReadOnlyList<Party>>)kv.Value.As<DamlList>().Values.Select(x => (IReadOnlyList<Party>)x.As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList()).ToList()),
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
