// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record AllocationResult
/// </summary>
public sealed record AllocationResult(
    [property: DamlFieldAttribute("output")] AllocationResult_Output Output,
    [property: DamlFieldAttribute("authorizerHoldingCids")] IReadOnlyDictionary<string, IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>> AuthorizerHoldingCids,
    [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta
) : IDamlRecord<AllocationResult>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("output", Output.ToVariant()),
        DamlField.Create("authorizerHoldingCids", new DamlTextMap(AuthorizerHoldingCids.ToDictionary(kv => kv.Key, kv => (DamlValue)new DamlList(kv.Value.Select(x => (DamlValue)x.ToDamlValue()).ToList())))),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationResult FromRecord(DamlRecord record) => new AllocationResult(
        Output: AllocationResult_Output.FromVariant(record.GetRequiredField("output").As<DamlVariant>()),
        AuthorizerHoldingCids: (IReadOnlyDictionary<string, IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>>)record.GetRequiredField("authorizerHoldingCids").As<DamlTextMap>().Values.ToDictionary(kv => kv.Key, kv => (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)kv.Value.As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList()),
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
