// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record AllocationResult_Output.AllocationResult_Pending
/// </summary>
public sealed record AllocationResult_Output_AllocationResult_Pending([property: DamlFieldAttribute("allocationCid")] ContractId<IAllocation> AllocationCid) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("allocationCid", AllocationCid.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationResult_Output_AllocationResult_Pending FromRecord(DamlRecord record) => new AllocationResult_Output_AllocationResult_Pending(
        AllocationCid: new ContractId<IAllocation>(record.GetRequiredField("allocationCid").As<DamlContractId>().Value)
    );

}
