// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml variant AllocationResult_Output
/// </summary>
public abstract record AllocationResult_Output : IDamlVariant
{
    /// <summary>Gets the variant constructor name.</summary>
    public abstract string Tag { get; }

    /// <summary>Converts to a DamlVariant.</summary>
    public abstract DamlVariant ToVariant();

    /// <summary>Reconstructs an AllocationResult_Output by dispatching on the DamlVariant constructor tag.</summary>
    public static AllocationResult_Output FromVariant(DamlVariant variant) =>
        variant.Constructor switch
        {
            "AllocationResult_Pending" => new AllocationResult_Pending(AllocationResult_Output_AllocationResult_Pending.FromRecord(variant.Value.As<DamlRecord>())),
            "AllocationResult_Settled" => new AllocationResult_Settled(AllocationResult_Output_AllocationResult_Settled.FromRecord(variant.Value.As<DamlRecord>())),
            "AllocationResult_Cancelled" => new AllocationResult_Cancelled(),
            "AllocationResult_Withdrawn" => new AllocationResult_Withdrawn(),
            _ => throw new ArgumentOutOfRangeException(nameof(variant), variant.Constructor, "Unknown AllocationResult_Output constructor")
        };

    /// <summary>AllocationResult_Pending constructor.</summary>
    public sealed record AllocationResult_Pending(AllocationResult_Output_AllocationResult_Pending Value) : AllocationResult_Output
    {
        /// <inheritdoc />
        public override string Tag => "AllocationResult_Pending";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AllocationResult_Pending", Value.ToRecord());
    }

    /// <summary>AllocationResult_Settled constructor.</summary>
    public sealed record AllocationResult_Settled(AllocationResult_Output_AllocationResult_Settled Value) : AllocationResult_Output
    {
        /// <inheritdoc />
        public override string Tag => "AllocationResult_Settled";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AllocationResult_Settled", Value.ToRecord());
    }

    /// <summary>AllocationResult_Cancelled constructor (no arguments).</summary>
    public sealed record AllocationResult_Cancelled() : AllocationResult_Output
    {
        /// <inheritdoc />
        public override string Tag => "AllocationResult_Cancelled";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AllocationResult_Cancelled", DamlUnit.Instance);
    }

    /// <summary>AllocationResult_Withdrawn constructor (no arguments).</summary>
    public sealed record AllocationResult_Withdrawn() : AllocationResult_Output
    {
        /// <inheritdoc />
        public override string Tag => "AllocationResult_Withdrawn";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AllocationResult_Withdrawn", DamlUnit.Instance);
    }

}
