// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record FinalizedAllocation
/// </summary>
public sealed record FinalizedAllocation([property: DamlFieldAttribute("allocationCid")] ContractId<IAllocation> AllocationCid, [property: DamlFieldAttribute("extraTransferLegSides")] IReadOnlyList<TransferLegSide> ExtraTransferLegSides, [property: DamlFieldAttribute("nextIterationFunding")] IReadOnlyDictionary<string, decimal>? NextIterationFunding) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("allocationCid", AllocationCid.ToDamlValue()),
        DamlField.Create("extraTransferLegSides", new DamlList(ExtraTransferLegSides.Select(x => (DamlValue)x.ToRecord()).ToList())),
        DamlField.Create("nextIterationFunding", NextIterationFunding is { } __NextIterationFunding ? new DamlOptional(new DamlTextMap(__NextIterationFunding.ToDictionary(kv => kv.Key, kv => (DamlValue)new DamlNumeric(kv.Value)))) : DamlOptional.None)
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static FinalizedAllocation FromRecord(DamlRecord record) => new FinalizedAllocation(
        AllocationCid: new ContractId<IAllocation>(record.GetRequiredField("allocationCid").As<DamlContractId>().Value),
        ExtraTransferLegSides: (IReadOnlyList<TransferLegSide>)record.GetRequiredField("extraTransferLegSides").As<DamlList>().Values.Select(x => TransferLegSide.FromRecord(x.As<DamlRecord>())).ToList(),
        NextIterationFunding: record.GetRequiredField("nextIterationFunding").AsOptional().HasValue ? (IReadOnlyDictionary<string, decimal>)record.GetRequiredField("nextIterationFunding").AsOptional().Value!.As<DamlTextMap>().Values.ToDictionary(kv => kv.Key, kv => kv.Value.As<DamlNumeric>().Value) : null
    );

}
