// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record SettlementFactory_SettleBatchResult
/// </summary>
public sealed record SettlementFactory_SettleBatchResult([property: DamlFieldAttribute("allocationSettleResults")] IReadOnlyList<AllocationResult> AllocationSettleResults, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("allocationSettleResults", new DamlList(AllocationSettleResults.Select(x => (DamlValue)x.ToRecord()).ToList())),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static SettlementFactory_SettleBatchResult FromRecord(DamlRecord record) => new SettlementFactory_SettleBatchResult(
        AllocationSettleResults: (IReadOnlyList<AllocationResult>)record.GetRequiredField("allocationSettleResults").As<DamlList>().Values.Select(x => AllocationResult.FromRecord(x.As<DamlRecord>())).ToList(),
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
