// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record SettlementFactoryView
/// </summary>
public sealed record SettlementFactoryView([property: DamlFieldAttribute("admin")] Party Admin, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("admin", Admin.ToDamlValue()),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static SettlementFactoryView FromRecord(DamlRecord record) => new SettlementFactoryView(
        Admin: Party.FromDamlValue(record.GetRequiredField("admin").As<DamlParty>()),
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
