// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record SettlementFactory_PublicFetch
/// </summary>
public sealed record SettlementFactory_PublicFetch([property: DamlFieldAttribute("actors")] IReadOnlyList<Party> Actors) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("actors", new DamlList(Actors.Select(x => (DamlValue)x.ToDamlValue()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static SettlementFactory_PublicFetch FromRecord(DamlRecord record) => new SettlementFactory_PublicFetch(
        Actors: (IReadOnlyList<Party>)record.GetRequiredField("actors").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList()
    );

}
