// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record SettlementInfo
/// </summary>
public sealed record SettlementInfo([property: DamlFieldAttribute("executors")] IReadOnlyList<Party> Executors, [property: DamlFieldAttribute("id")] string Id, [property: DamlFieldAttribute("cid")] ContractId<Splice.Api.Token.Metadata.V1.IAnyContract>? Cid, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("executors", new DamlList(Executors.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("id", new DamlText(Id)),
        DamlField.Create("cid", Cid is { } __Cid ? new DamlOptional(__Cid.ToDamlValue()) : DamlOptional.None),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static SettlementInfo FromRecord(DamlRecord record) => new SettlementInfo(
        Executors: (IReadOnlyList<Party>)record.GetRequiredField("executors").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList(),
        Id: record.GetRequiredField("id").As<DamlText>().Value,
        Cid: record.GetRequiredField("cid").AsOptional().HasValue ? new ContractId<Splice.Api.Token.Metadata.V1.IAnyContract>(record.GetRequiredField("cid").AsOptional().Value!.As<DamlContractId>().Value) : null,
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
