// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.V2;

/// <summary>
/// Generated from Daml record TransferLeg
/// </summary>
public sealed record TransferLeg([property: DamlFieldAttribute("transferLegId")] string TransferLegId, [property: DamlFieldAttribute("sender")] Splice.Api.Token.Holding.V2.Account Sender, [property: DamlFieldAttribute("receiver")] Splice.Api.Token.Holding.V2.Account Receiver, [property: DamlFieldAttribute("amount")] decimal Amount, [property: DamlFieldAttribute("instrumentId")] string InstrumentId, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("transferLegId", new DamlText(TransferLegId)),
        DamlField.Create("sender", Sender.ToRecord()),
        DamlField.Create("receiver", Receiver.ToRecord()),
        DamlField.Create("amount", new DamlNumeric(Amount)),
        DamlField.Create("instrumentId", new DamlText(InstrumentId)),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferLeg FromRecord(DamlRecord record) => new TransferLeg(
        TransferLegId: record.GetRequiredField("transferLegId").As<DamlText>().Value,
        Sender: Splice.Api.Token.Holding.V2.Account.FromRecord(record.GetRequiredField("sender").As<DamlRecord>()),
        Receiver: Splice.Api.Token.Holding.V2.Account.FromRecord(record.GetRequiredField("receiver").As<DamlRecord>()),
        Amount: record.GetRequiredField("amount").As<DamlNumeric>().Value,
        InstrumentId: record.GetRequiredField("instrumentId").As<DamlText>().Value,
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
