// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Holding.V2;

/// <summary>
/// Generated from Daml record Account
/// </summary>
public sealed record Account([property: DamlFieldAttribute("owner")] Party? Owner, [property: DamlFieldAttribute("provider")] Party? Provider, [property: DamlFieldAttribute("id")] string Id) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("owner", Owner is { } __Owner ? new DamlOptional(__Owner.ToDamlValue()) : DamlOptional.None),
        DamlField.Create("provider", Provider is { } __Provider ? new DamlOptional(__Provider.ToDamlValue()) : DamlOptional.None),
        DamlField.Create("id", new DamlText(Id))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static Account FromRecord(DamlRecord record) => new Account(
        Owner: record.GetRequiredField("owner").AsOptional().HasValue ? Party.FromDamlValue(record.GetRequiredField("owner").AsOptional().Value!.As<DamlParty>()) : null,
        Provider: record.GetRequiredField("provider").AsOptional().HasValue ? Party.FromDamlValue(record.GetRequiredField("provider").AsOptional().Value!.As<DamlParty>()) : null,
        Id: record.GetRequiredField("id").As<DamlText>().Value
    );

}
