// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml template Splice.Ans:AnsEntry
/// </summary>
public sealed partial record AnsEntry(
    [property: DamlFieldAttribute("user")] Party User,
    [property: DamlFieldAttribute("dso")] Party Dso,
    [property: DamlFieldAttribute("name")] string Name,
    [property: DamlFieldAttribute("url")] string Url,
    [property: DamlFieldAttribute("description")] string Description,
    [property: DamlFieldAttribute("expiresAt")] DateTimeOffset ExpiresAt
) : ITemplate, IHasChoices<AnsEntry>, IDamlRecord<AnsEntry>
{
    /// <summary>Gets the template identifier.</summary>
    public static Identifier TemplateId { get; } = new("cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1", "Splice.Ans", "AnsEntry");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static Version PackageVersion { get; } = new(0, 1, 24);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("user", User.ToDamlValue()),
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("name", new DamlText(Name)),
        DamlField.Create("url", new DamlText(Url)),
        DamlField.Create("description", new DamlText(Description)),
        DamlField.Create("expiresAt", new DamlTimestamp(ExpiresAt))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntry FromRecord(DamlRecord record) => new AnsEntry(
        User: Party.FromDamlValue(record.GetRequiredField("user").As<DamlParty>()),
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        Name: record.GetRequiredField("name").As<DamlText>().Value,
        Url: record.GetRequiredField("url").As<DamlText>().Value,
        Description: record.GetRequiredField("description").As<DamlText>().Value,
        ExpiresAt: record.GetRequiredField("expiresAt").As<DamlTimestamp>().Value
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("user", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "user"), context.Field("user"))),
            DamlField.Create("dso", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "dso"), context.Field("dso"))),
            DamlField.Create("name", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "name"), context.Field("name"))),
            DamlField.Create("url", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "url"), context.Field("url"))),
            DamlField.Create("description", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "description"), context.Field("description"))),
            DamlField.Create("expiresAt", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTimestamp(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "expiresAt"), context.Field("expiresAt")))
        );
    }

    /// <summary>
    /// Exercise the AnsEntry_Expire choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsEntry, AnsEntry_Expire, AnsEntry_ExpireResult> ChoiceAnsEntry_Expire { get; } = new()
    {
        Name = new ChoiceName("AnsEntry_Expire"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsEntry_Expire.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => AnsEntry_ExpireResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => AnsEntry.AnsEntry_Expire.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => AnsEntry_ExpireResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsEntry_Renew choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsEntry, AnsEntry_Renew, AnsEntry_RenewResult> ChoiceAnsEntry_Renew { get; } = new()
    {
        Name = new ChoiceName("AnsEntry_Renew"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsEntry_Renew.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => AnsEntry_RenewResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => AnsEntry.AnsEntry_Renew.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => AnsEntry_RenewResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsEntry, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlRecord.Create(),
        ArgumentDecoder = val => val is DamlRecord { Fields.Count: 0 } ? DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    public static IReadOnlyList<IChoice> Choices { get; } = [ChoiceAnsEntry_Expire, ChoiceAnsEntry_Renew, ChoiceArchive];

    /// <summary>Contract ID for AnsEntry.</summary>
    [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Daml.Runtime.Serialization.ContractIdJsonConverterFactory))]
    public sealed record ContractId(string Value) : ContractId<AnsEntry>(Value), IExercises<AnsEntry>
    {
        ContractId<AnsEntry> IExercises<AnsEntry>.ContractId => this;
    }

    /// <summary>Active contract for AnsEntry.</summary>
    public sealed record Contract(ContractId Id, AnsEntry Data) : IContract<ContractId, AnsEntry>
    {
        /// <summary>Creates a Contract from a CreatedEvent.</summary>
        public static Contract FromCreatedEvent(CreatedEvent @event) =>
            new(new ContractId(@event.ContractId), global::Splice.Ans.AnsEntry.FromRecord(@event.CreateArguments));
    }
}


/// <summary>
/// Typed-submitter extensions for <see cref="AnsEntry"/>. The
/// <see cref="CreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AnsEntrySubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AnsEntry"/> contract on the ledger.
    /// The submitter is passed explicitly via <paramref name="submitter"/>. The static
    /// analyzer could not resolve the Daml <c>signatory</c> clause to payload-field
    /// references — typically because the expression involves the template key, a
    /// constant, or a function call. <see cref="SubmitterInfo"/> implicitly converts
    /// from a single <c>Party</c>, so single-party callers still pass one literal.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<ContractId<AnsEntry>>> CreateAsync(
        this ILedgerWriter client,
        AnsEntry payload,
        SubmitterInfo submitter,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(payload);

        return client.TryCreateAsync<AnsEntry>(payload, submitter, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="AnsEntry"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AnsEntryNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsEntry_Expire choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AnsEntry_ExpireCommand(
        this ContractId<AnsEntry> contractId,
        AnsEntry.AnsEntry_Expire argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AnsEntry.TemplateId,
            contractId,
            new ChoiceName("AnsEntry_Expire"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsEntry_Expire choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsEntry_ExpireResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsEntry_ExpireResult>> AnsEntry_ExpireAsync(
        this ContractId<AnsEntry> contractId,
        ILedgerWriter client,
        AnsEntry.AnsEntry_Expire argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsEntry_ExpireCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsEntry_ExpireResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsEntry_Renew choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AnsEntry_RenewCommand(
        this ContractId<AnsEntry> contractId,
        AnsEntry.AnsEntry_Renew argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AnsEntry.TemplateId,
            contractId,
            new ChoiceName("AnsEntry_Renew"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsEntry_Renew choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsEntry_RenewResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsEntry_RenewResult>> AnsEntry_RenewAsync(
        this ContractId<AnsEntry> contractId,
        ILedgerWriter client,
        AnsEntry.AnsEntry_Renew argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsEntry_RenewCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsEntry_RenewResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<AnsEntry> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return new ExerciseCommand(
            AnsEntry.TemplateId,
            contractId,
            new ChoiceName("Archive"),
            DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>Unit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<Unit>> ArchiveAsync(
        this ContractId<AnsEntry> contractId,
        ILedgerWriter client,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static ExerciseOutcome<AnsEntry_ExpireResult> ProjectAnsEntry_ExpireResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntry.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntry.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsEntry_Expire", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = AnsEntry.ChoiceAnsEntry_Expire.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AnsEntry_ExpireResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AnsEntry_ExpireResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsEntry_Expire' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsEntry_RenewResult> ProjectAnsEntry_RenewResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntry.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntry.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsEntry_Renew", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = AnsEntry.ChoiceAnsEntry_Renew.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AnsEntry_RenewResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AnsEntry_RenewResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsEntry_Renew' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<Unit> ProjectArchiveResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntry.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntry.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "Archive", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = Unit.Value;
                    return new ExerciseOutcome<Unit>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<Unit>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'Archive' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
