// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml record AnsEntry_ExpireResult
/// </summary>
public sealed record AnsEntry_ExpireResult : IDamlRecord<AnsEntry_ExpireResult>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create();

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntry_ExpireResult FromRecord(DamlRecord record) => new AnsEntry_ExpireResult();

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create();
    }

}
