// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using Daml.Runtime.Stdlib;

namespace Splice.Ans;

public sealed partial record AnsEntry
{
    /// <summary>
    /// Choice argument type for AnsEntry_Renew.
    /// </summary>
    public sealed record AnsEntry_Renew(
        [property: DamlFieldAttribute("extension")] RelTime Extension
    ) : IDamlRecord<AnsEntry_Renew>
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("extension", Extension.ToRecord())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AnsEntry_Renew FromRecord(DamlRecord record) => new AnsEntry_Renew(
            Extension: RelTime.FromRecord(record.GetRequiredField("extension").As<DamlRecord>())
        );

        /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return DamlRecord.Create(
                DamlField.Create("extension", RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "extension"), context.Field("extension")))
            );
        }

    }
}
