// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml template Splice.Ans:AnsRules
/// </summary>
public sealed partial record AnsRules(
    [property: DamlFieldAttribute("dso")] Party Dso,
    [property: DamlFieldAttribute("config")] AnsRulesConfig Config
) : ITemplate, IHasChoices<AnsRules>, IDamlRecord<AnsRules>
{
    /// <summary>Gets the template identifier.</summary>
    public static Identifier TemplateId { get; } = new("cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1", "Splice.Ans", "AnsRules");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "cc7d11e790174d2b18ad3e148d8762340e58de35616b399f9397a1b1d5b752f1";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static Version PackageVersion { get; } = new(0, 1, 24);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("config", Config.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsRules FromRecord(DamlRecord record) => new AnsRules(
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        Config: AnsRulesConfig.FromRecord(record.GetRequiredField("config").As<DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("dso", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "dso"), context.Field("dso"))),
            DamlField.Create("config", AnsRulesConfig.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "config"), context.Field("config")))
        );
    }

    /// <summary>
    /// Exercise the AnsRules_CollectEntryRenewalPayment choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_CollectEntryRenewalPayment, AnsRules_CollectEntryRenewalPaymentResult> ChoiceAnsRules_CollectEntryRenewalPayment { get; } = new()
    {
        Name = new ChoiceName("AnsRules_CollectEntryRenewalPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_CollectEntryRenewalPayment.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => AnsRules_CollectEntryRenewalPaymentResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => AnsRules.AnsRules_CollectEntryRenewalPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => AnsRules_CollectEntryRenewalPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsRules_CollectInitialEntryPayment choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_CollectInitialEntryPayment, AnsRules_CollectInitialEntryPaymentResult> ChoiceAnsRules_CollectInitialEntryPayment { get; } = new()
    {
        Name = new ChoiceName("AnsRules_CollectInitialEntryPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_CollectInitialEntryPayment.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => AnsRules_CollectInitialEntryPaymentResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => AnsRules.AnsRules_CollectInitialEntryPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => AnsRules_CollectInitialEntryPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsRules_RejectEntryInitialPayment choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_RejectEntryInitialPayment, AnsRules_RejectEntryInitialPaymentResult> ChoiceAnsRules_RejectEntryInitialPayment { get; } = new()
    {
        Name = new ChoiceName("AnsRules_RejectEntryInitialPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_RejectEntryInitialPayment.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => AnsRules_RejectEntryInitialPaymentResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => AnsRules.AnsRules_RejectEntryInitialPayment.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => AnsRules_RejectEntryInitialPaymentResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AnsRules_RequestEntry choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_RequestEntry, AnsRules_RequestEntryResult> ChoiceAnsRules_RequestEntry { get; } = new()
    {
        Name = new ChoiceName("AnsRules_RequestEntry"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => AnsRules_RequestEntry.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => AnsRules_RequestEntryResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => AnsRules.AnsRules_RequestEntry.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => AnsRules_RequestEntryResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsRules, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlRecord.Create(),
        ArgumentDecoder = val => val is DamlRecord { Fields.Count: 0 } ? DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    public static IReadOnlyList<IChoice> Choices { get; } = [ChoiceAnsRules_CollectEntryRenewalPayment, ChoiceAnsRules_CollectInitialEntryPayment, ChoiceAnsRules_RejectEntryInitialPayment, ChoiceAnsRules_RequestEntry, ChoiceArchive];

    /// <summary>Contract ID for AnsRules.</summary>
    [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Daml.Runtime.Serialization.ContractIdJsonConverterFactory))]
    public sealed record ContractId(string Value) : ContractId<AnsRules>(Value), IExercises<AnsRules>
    {
        ContractId<AnsRules> IExercises<AnsRules>.ContractId => this;
    }

    /// <summary>Active contract for AnsRules.</summary>
    public sealed record Contract(ContractId Id, AnsRules Data) : IContract<ContractId, AnsRules>
    {
        /// <summary>Creates a Contract from a CreatedEvent.</summary>
        public static Contract FromCreatedEvent(CreatedEvent @event) =>
            new(new ContractId(@event.ContractId), global::Splice.Ans.AnsRules.FromRecord(@event.CreateArguments));
    }
}


/// <summary>
/// Typed-submitter extensions for <see cref="AnsRules"/>. The
/// <see cref="CreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AnsRulesSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AnsRules"/> contract on the ledger.
    /// The submitting parties are derived from the payload — each Daml signatory is
    /// a reference to a payload field, so the caller never restates a party that's
    /// already in the record.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<ContractId<AnsRules>>> CreateAsync(
        this ILedgerWriter client,
        AnsRules payload,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(payload);

        SubmitterInfo submitter = payload.Dso;

        return client.TryCreateAsync<AnsRules>(payload, submitter, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="AnsRules"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AnsRulesNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_CollectEntryRenewalPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AnsRules_CollectEntryRenewalPaymentCommand(
        this ContractId<AnsRules> contractId,
        AnsRules.AnsRules_CollectEntryRenewalPayment argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_CollectEntryRenewalPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_CollectEntryRenewalPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_CollectEntryRenewalPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>> AnsRules_CollectEntryRenewalPaymentAsync(
        this ContractId<AnsRules> contractId,
        ILedgerWriter client,
        AnsRules.AnsRules_CollectEntryRenewalPayment argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_CollectEntryRenewalPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_CollectEntryRenewalPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_CollectInitialEntryPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AnsRules_CollectInitialEntryPaymentCommand(
        this ContractId<AnsRules> contractId,
        AnsRules.AnsRules_CollectInitialEntryPayment argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_CollectInitialEntryPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_CollectInitialEntryPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_CollectInitialEntryPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>> AnsRules_CollectInitialEntryPaymentAsync(
        this ContractId<AnsRules> contractId,
        ILedgerWriter client,
        AnsRules.AnsRules_CollectInitialEntryPayment argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_CollectInitialEntryPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_CollectInitialEntryPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_RejectEntryInitialPayment choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AnsRules_RejectEntryInitialPaymentCommand(
        this ContractId<AnsRules> contractId,
        AnsRules.AnsRules_RejectEntryInitialPayment argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_RejectEntryInitialPayment"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_RejectEntryInitialPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_RejectEntryInitialPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>> AnsRules_RejectEntryInitialPaymentAsync(
        this ContractId<AnsRules> contractId,
        ILedgerWriter client,
        AnsRules.AnsRules_RejectEntryInitialPayment argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_RejectEntryInitialPaymentCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_RejectEntryInitialPaymentResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AnsRules_RequestEntry choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AnsRules_RequestEntryCommand(
        this ContractId<AnsRules> contractId,
        AnsRules.AnsRules_RequestEntry argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_RequestEntry"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AnsRules_RequestEntry choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_RequestEntryResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_RequestEntryResult>> AnsRules_RequestEntryAsync(
        this ContractId<AnsRules> contractId,
        ILedgerWriter client,
        AnsRules.AnsRules_RequestEntry argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AnsRules_RequestEntryCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAnsRules_RequestEntryResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<AnsRules> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("Archive"),
            DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>Unit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<Unit>> ArchiveAsync(
        this ContractId<AnsRules> contractId,
        ILedgerWriter client,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult> ProjectAnsRules_CollectEntryRenewalPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_CollectEntryRenewalPayment", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = AnsRules.ChoiceAnsRules_CollectEntryRenewalPayment.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_CollectEntryRenewalPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult> ProjectAnsRules_CollectInitialEntryPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_CollectInitialEntryPayment", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = AnsRules.ChoiceAnsRules_CollectInitialEntryPayment.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_CollectInitialEntryPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult> ProjectAnsRules_RejectEntryInitialPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_RejectEntryInitialPayment", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = AnsRules.ChoiceAnsRules_RejectEntryInitialPayment.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_RejectEntryInitialPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsRules_RequestEntryResult> ProjectAnsRules_RequestEntryResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_RequestEntry", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = AnsRules.ChoiceAnsRules_RequestEntry.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AnsRules_RequestEntryResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AnsRules_RequestEntryResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_RequestEntry' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<Unit> ProjectArchiveResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "Archive", StringComparison.Ordinal))
            {
                try
                {
                    var decoded = Unit.Value;
                    return new ExerciseOutcome<Unit>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<Unit>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'Archive' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
