// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using Daml.Runtime.Stdlib;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml record AnsRulesConfig
/// </summary>
public sealed record AnsRulesConfig(
    [property: DamlFieldAttribute("renewalDuration")] RelTime RenewalDuration,
    [property: DamlFieldAttribute("entryLifetime")] RelTime EntryLifetime,
    [property: DamlFieldAttribute("entryFee")] decimal EntryFee,
    [property: DamlFieldAttribute("descriptionPrefix")] string DescriptionPrefix
) : IDamlRecord<AnsRulesConfig>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("renewalDuration", RenewalDuration.ToRecord()),
        DamlField.Create("entryLifetime", EntryLifetime.ToRecord()),
        DamlField.Create("entryFee", new DamlNumeric(EntryFee)),
        DamlField.Create("descriptionPrefix", new DamlText(DescriptionPrefix))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsRulesConfig FromRecord(DamlRecord record) => new AnsRulesConfig(
        RenewalDuration: RelTime.FromRecord(record.GetRequiredField("renewalDuration").As<DamlRecord>()),
        EntryLifetime: RelTime.FromRecord(record.GetRequiredField("entryLifetime").As<DamlRecord>()),
        EntryFee: record.GetRequiredField("entryFee").As<DamlNumeric>().Value,
        DescriptionPrefix: record.GetRequiredField("descriptionPrefix").As<DamlText>().Value
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("renewalDuration", RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "renewalDuration"), context.Field("renewalDuration"))),
            DamlField.Create("entryLifetime", RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "entryLifetime"), context.Field("entryLifetime"))),
            DamlField.Create("entryFee", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadNumeric(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "entryFee"), context.Field("entryFee"))),
            DamlField.Create("descriptionPrefix", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "descriptionPrefix"), context.Field("descriptionPrefix")))
        );
    }

}
