// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Ans;

public sealed partial record AnsRules
{
    /// <summary>
    /// Choice argument type for AnsRules_CollectEntryRenewalPayment.
    /// </summary>
    public sealed record AnsRules_CollectEntryRenewalPayment(
        [property: DamlFieldAttribute("user")] Party User,
        [property: DamlFieldAttribute("entryContext")] ContractId<AnsEntryContext> EntryContext,
        [property: DamlFieldAttribute("paymentCid")] ContractId<global::Splice.Wallet.Subscriptions.SubscriptionPayment> PaymentCid,
        [property: DamlFieldAttribute("entryCid")] ContractId<AnsEntry> EntryCid,
        [property: DamlFieldAttribute("transferContext")] global::Splice.AmuletRules.AppTransferContext TransferContext
    ) : IDamlRecord
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("user", User.ToDamlValue()),
            DamlField.Create("entryContext", EntryContext.ToDamlValue()),
            DamlField.Create("paymentCid", PaymentCid.ToDamlValue()),
            DamlField.Create("entryCid", EntryCid.ToDamlValue()),
            DamlField.Create("transferContext", TransferContext.ToRecord())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AnsRules_CollectEntryRenewalPayment FromRecord(DamlRecord record) => new AnsRules_CollectEntryRenewalPayment(
            User: Party.FromDamlValue(record.GetRequiredField("user").As<DamlParty>()),
            EntryContext: new ContractId<AnsEntryContext>(record.GetRequiredField("entryContext").As<DamlContractId>().Value),
            PaymentCid: new ContractId<global::Splice.Wallet.Subscriptions.SubscriptionPayment>(record.GetRequiredField("paymentCid").As<DamlContractId>().Value),
            EntryCid: new ContractId<AnsEntry>(record.GetRequiredField("entryCid").As<DamlContractId>().Value),
            TransferContext: global::Splice.AmuletRules.AppTransferContext.FromRecord(record.GetRequiredField("transferContext").As<DamlRecord>())
        );

    }
}
