// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Ans;

public sealed partial record AnsRules
{
    /// <summary>
    /// Choice argument type for AnsRules_CollectInitialEntryPayment.
    /// </summary>
    public sealed record AnsRules_CollectInitialEntryPayment(
        [property: DamlFieldAttribute("user")] Party User,
        [property: DamlFieldAttribute("entryContext")] ContractId<AnsEntryContext> EntryContext,
        [property: DamlFieldAttribute("paymentCid")] ContractId<global::Splice.Wallet.Subscriptions.SubscriptionInitialPayment> PaymentCid,
        [property: DamlFieldAttribute("transferContext")] global::Splice.AmuletRules.AppTransferContext TransferContext
    ) : IDamlRecord<AnsRules_CollectInitialEntryPayment>
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("user", User.ToDamlValue()),
            DamlField.Create("entryContext", EntryContext.ToDamlValue()),
            DamlField.Create("paymentCid", PaymentCid.ToDamlValue()),
            DamlField.Create("transferContext", TransferContext.ToRecord())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AnsRules_CollectInitialEntryPayment FromRecord(DamlRecord record) => new AnsRules_CollectInitialEntryPayment(
            User: Party.FromDamlValue(record.GetRequiredField("user").As<DamlParty>()),
            EntryContext: new ContractId<AnsEntryContext>(record.GetRequiredField("entryContext").As<DamlContractId>().Value),
            PaymentCid: new ContractId<global::Splice.Wallet.Subscriptions.SubscriptionInitialPayment>(record.GetRequiredField("paymentCid").As<DamlContractId>().Value),
            TransferContext: global::Splice.AmuletRules.AppTransferContext.FromRecord(record.GetRequiredField("transferContext").As<DamlRecord>())
        );

        /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return DamlRecord.Create(
                DamlField.Create("user", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "user"), context.Field("user"))),
                DamlField.Create("entryContext", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "entryContext"), context.Field("entryContext"))),
                DamlField.Create("paymentCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "paymentCid"), context.Field("paymentCid"))),
                DamlField.Create("transferContext", global::Splice.AmuletRules.AppTransferContext.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "transferContext"), context.Field("transferContext")))
            );
        }

    }
}
