// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Ans;

/// <summary>
/// Generated from Daml record ExpectedPayment
/// </summary>
public sealed record ExpectedPayment(
    [property: DamlFieldAttribute("dso")] Party Dso,
    [property: DamlFieldAttribute("sender")] Party Sender
) : IDamlRecord<ExpectedPayment>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("sender", Sender.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static ExpectedPayment FromRecord(DamlRecord record) => new ExpectedPayment(
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        Sender: Party.FromDamlValue(record.GetRequiredField("sender").As<DamlParty>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("dso", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "dso"), context.Field("dso"))),
            DamlField.Create("sender", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "sender"), context.Field("sender")))
        );
    }

}
