// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Crossmodulecollision;

/// <summary>
/// Generated from Daml template CollisionB:Offer
/// </summary>
public sealed partial record Offer(
    [property: DamlFieldAttribute("owner")] Party Owner,
    [property: DamlFieldAttribute("memo")] string Memo
) : ITemplate, IDamlRecord<Offer>
{
    /// <summary>Gets the template identifier.</summary>
    public static Identifier TemplateId { get; } = new("5a7215d354b1b18068c2f264b60dcab8d8a0df37b02c7fcb19d1f051333d75d1", "CollisionB", "Offer");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "5a7215d354b1b18068c2f264b60dcab8d8a0df37b02c7fcb19d1f051333d75d1";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "crossmodulecollision";

    /// <summary>Gets the package version.</summary>
    public static Version PackageVersion { get; } = new(0, 0, 1);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("owner", Owner.ToDamlValue()),
        DamlField.Create("memo", new DamlText(Memo))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static Offer FromRecord(DamlRecord record) => new Offer(
        Owner: Party.FromDamlValue(record.GetRequiredField("owner").As<DamlParty>()),
        Memo: record.GetRequiredField("memo").As<DamlText>().Value
    );

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<Offer, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlRecord.Create(),
        ResultDecoder = _ => DamlUnit.Instance
    };

    /// <summary>
    /// Exercise the Retag choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<Offer, Retag, ContractId<Offer>> ChoiceRetag { get; } = new()
    {
        Name = new ChoiceName("Retag"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => new ContractId<Offer>(val.As<DamlContractId>().Value)
    };

    /// <summary>Contract ID for Offer.</summary>
    [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Daml.Runtime.Serialization.ContractIdJsonConverterFactory))]
    public sealed record ContractId(string Value) : ContractId<Offer>(Value), IExercises<Offer>
    {
        ContractId<Offer> IExercises<Offer>.ContractId => this;
    }

    /// <summary>Active contract for Offer.</summary>
    public sealed record Contract(ContractId Id, Offer Data) : IContract<ContractId, Offer>
    {
        /// <summary>Creates a Contract from a CreatedEvent.</summary>
        public static Contract FromCreatedEvent(CreatedEvent @event) =>
            new(new ContractId(@event.ContractId), global::Crossmodulecollision.Offer.FromRecord(@event.CreateArguments));
    }
}

/// <summary>
/// Typed projection of the contracts created by the Retag choice.
/// One field per template the choice creates; cardinality follows the choice's
/// return type (single, optional, list).
/// </summary>
public sealed record RetagResult(
    ContractId<Offer> Offer
)
{
    /// <summary>
    /// Projects an upstream transaction's created contracts to a typed <see cref="RetagResult"/>.
    /// Returns:
    /// <list type="bullet">
    ///   <item><see cref="ExerciseOutcome{T}.One"/> when every expected template's cardinality matches.</item>
    ///   <item><see cref="ExerciseOutcome{T}.None"/> when at least one required slot's template is missing from the transaction.</item>
    ///   <item><see cref="ExerciseOutcome{T}.Many"/> when a single-cardinality slot has more than one created contract of its template, or an optional-cardinality slot has more than one.</item>
    /// </list>
    /// Cardinality is matched by template ID's <c>(module, entity)</c> pair only — package upgrades that share the same logical template name match cleanly.
    /// </summary>
    public static ExerciseOutcome<RetagResult> FromCreatedContracts(IEnumerable<CreatedContract> created)
    {
        ArgumentNullException.ThrowIfNull(created);
        var templateMatches0 = new List<string>();
        foreach (var item in created)
        {
            if (string.Equals(item.TemplateId.ModuleName, global::Crossmodulecollision.Offer.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(item.TemplateId.EntityName, global::Crossmodulecollision.Offer.TemplateId.EntityName, StringComparison.Ordinal))
            {
                templateMatches0.Add(item.ContractId);
            }
        }
        var matches0 = new List<string>();
        var templateMatchIndex0 = 0;
        if (templateMatchIndex0 < templateMatches0.Count)
        {
            matches0.Add(templateMatches0[templateMatchIndex0]);
            templateMatchIndex0++;
        }
        while (templateMatchIndex0 < templateMatches0.Count)
        {
            matches0.Add(templateMatches0[templateMatchIndex0]);
            templateMatchIndex0++;
        }

        if (matches0.Count == 0)
        {
            return new ExerciseOutcome<RetagResult>.None();
        }
        if (matches0.Count > 1)
        {
            return new ExerciseOutcome<RetagResult>.Many(matches0.Count, matches0);
        }

        return new ExerciseOutcome<RetagResult>.One(new RetagResult(
            Offer: new ContractId<global::Crossmodulecollision.Offer>(matches0[0])
        ));
    }

}


/// <summary>
/// Static <c>&lt;Choice&gt;Async</c> extension methods for <see cref="Offer"/>.
/// One method per create-bearing choice; each delegates to
/// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
/// and projects success via <c>&lt;Choice&gt;Result.FromCreatedContracts</c>.
/// </summary>
public static class OfferExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Retag choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand RetagCommand(
        this ContractId<Offer> contractId,
        Offer.Retag argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            Offer.TemplateId,
            contractId,
            new ChoiceName("Retag"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the Retag choice and projects the resulting transaction's created contracts to a typed <see cref="RetagResult"/>.
    /// One <c>Party</c> parameter is emitted per Daml controller (declaration order).
    /// The wrapper builds a <see cref="SubmitterInfo"/> from those parties before
    /// dispatching to <c>ILedgerWriter</c>.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="owner">Controller party from the Daml <c>controller</c> clause, routed into the submission's <c>actAs</c> set.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<RetagResult>> RetagAsync(
        this ContractId<Offer> contractId,
        ILedgerWriter client,
        Offer.Retag argument,
        Party owner,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        SubmitterInfo submitter = owner;

        return contractId.RetagAsync(
            client,
            argument,
            submitter,
            workflowId,
            commandId,
            timeout,
            cancellationToken);
    }

    /// <summary>
    /// Exercises the Retag choice with an explicit <see cref="SubmitterInfo"/> and projects the resulting transaction's created contracts to a typed <see cref="RetagResult"/>.
    /// Companion to the named-<c>Party</c> overload for the case where the submitter must
    /// read contracts it does not act as — the choice's created contracts are visible to an
    /// observer but not to the submitter, so the caller supplies the <c>readAs</c> parties.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<RetagResult>> RetagAsync(
        this ContractId<Offer> contractId,
        ILedgerWriter client,
        Offer.Retag argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.RetagCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => RetagResult.FromCreatedContracts(tx.CreatedContracts));
    }

    /// <summary>
    /// Exercises the Retag choice on a fetched <see cref="Offer"/> contract,
    /// reading every controller and observer party off the contract payload so the
    /// caller passes no parties. Delegates to the
    /// <c>ContractId&lt;Offer&gt;</c> overload.
    /// </summary>
    /// <param name="contract">The fetched contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<RetagResult>> RetagAsync(
        this Offer.Contract contract,
        ILedgerWriter client,
        Offer.Retag argument,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contract);
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(argument);

        return contract.Id.RetagAsync(
            client,
            argument,
            contract.Data.Owner,
            workflowId,
            commandId,
            timeout,
            cancellationToken);
    }

    /// <summary>
    /// Exercises the Retag choice on a fetched <see cref="Offer"/> contract with an
    /// explicit <see cref="SubmitterInfo"/>. Companion to the payload-derived overload for
    /// multi-party submissions and for callers who must supply <c>readAs</c> parties the
    /// payload cannot name. Delegates to the
    /// <c>ContractId&lt;Offer&gt;</c> overload.
    /// </summary>
    /// <param name="contract">The fetched contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<RetagResult>> RetagAsync(
        this Offer.Contract contract,
        ILedgerWriter client,
        Offer.Retag argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contract);
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(argument);

        return contract.Id.RetagAsync(
            client,
            argument,
            submitter,
            workflowId,
            commandId,
            timeout,
            cancellationToken);
    }
}

/// <summary>
/// Typed-submitter extensions for <see cref="Offer"/>. The
/// <see cref="CreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class OfferSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="Offer"/> contract on the ledger.
    /// The submitting parties are derived from the payload — each Daml signatory is
    /// a reference to a payload field, so the caller never restates a party that's
    /// already in the record.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<ContractId<Offer>>> CreateAsync(
        this ILedgerWriter client,
        Offer payload,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(payload);

        SubmitterInfo submitter = payload.Owner;

        return client.TryCreateAsync<Offer>(payload, submitter, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="Offer"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class OfferNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<Offer> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return new ExerciseCommand(
            Offer.TemplateId,
            contractId,
            new ChoiceName("Archive"),
            DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>Unit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<Unit>> ArchiveAsync(
        this ContractId<Offer> contractId,
        ILedgerWriter client,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static ExerciseOutcome<Unit> ProjectArchiveResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, Offer.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, Offer.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "Archive", StringComparison.Ordinal))
            {
                return new ExerciseOutcome<Unit>.One(Unit.Value);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'Archive' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
