// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Crossmodulecollision;

public sealed partial record Offer
{
    /// <summary>
    /// Choice argument type for Retag.
    /// </summary>
    public sealed record Retag(
        [property: DamlFieldAttribute("label")] string Label,
        [property: DamlFieldAttribute("count")] long Count
    ) : IDamlRecord
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("label", new DamlText(Label)),
            DamlField.Create("count", new DamlInt64(Count))
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static Retag FromRecord(DamlRecord record) => new Retag(
            Label: record.GetRequiredField("label").As<DamlText>().Value,
            Count: record.GetRequiredField("count").As<DamlInt64>().Value
        );

    }
}
