// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Generated from Daml interface Splice.Api.Token.TransferInstructionV2:TransferFactory
/// </summary>
/// <remarks>
/// Instance properties mirror the fields of the interface view <see cref="TransferFactoryView"/>,
/// which implements this marker, so a view can be read through a marker-typed variable.
/// <c>==</c> between marker-typed variables compares by reference equality; view payloads
/// materialize as concrete <see cref="TransferFactoryView"/> values, whose record value equality
/// applies once concretely typed.
/// </remarks>
public interface ITransferFactory : IDamlInterface, IHasView<TransferFactoryView>
{
    /// <summary>Gets the interface identifier.</summary>
    static Identifier IDamlInterface.InterfaceId => InterfaceId;

    /// <summary>Gets the interface identifier.</summary>
    public static new Identifier InterfaceId { get; } = new("29317e3b7b165d2bbf16721bcca0ec4869e53eddb2738bddf790d61af28e0099", "Splice.Api.Token.TransferInstructionV2", "TransferFactory");

    /// <summary>Gets the package ID.</summary>
    static string IDamlInterface.PackageId => "29317e3b7b165d2bbf16721bcca0ec4869e53eddb2738bddf790d61af28e0099";

    /// <summary>Gets the package name.</summary>
    static string IDamlInterface.PackageName => "splice-api-token-transfer-instruction-v2";

    /// <summary>Gets the package version.</summary>
    static Version IDamlInterface.PackageVersion => new(1, 0, 0);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    static DamlTypeDescriptor global::Daml.Runtime.IDamlType.DamlTypeId => new(new Identifier("29317e3b7b165d2bbf16721bcca0ec4869e53eddb2738bddf790d61af28e0099", "Splice.Api.Token.TransferInstructionV2", "TransferFactory"), DamlTypeKind.Interface, "splice-api-token-transfer-instruction-v2");

    /// <summary>Gets the pure type witness pairing this marker with its view record <see cref="TransferFactoryView"/>; passing it to a generic method infers both type parameters from one argument.</summary>
    public static ViewDescriptor<ITransferFactory, TransferFactoryView> View { get; } = new();

    /// <summary>Gets the admin field of the interface view.</summary>
    Party Admin { get; }

    /// <summary>Gets the meta field of the interface view.</summary>
    Splice.Api.Token.Metadata.V1.Metadata Meta { get; }

}

/// <summary>
/// Static <c>&lt;Choice&gt;Async</c> extension methods for the <c>TransferFactory</c> Daml interface.
/// One method per choice; each submits an interface-typed
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> built via
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand.ForInterface{TInterface}(global::Daml.Runtime.Contracts.ContractId{TInterface},global::Daml.Runtime.Commands.ChoiceName,global::Daml.Runtime.Data.DamlValue)"/>
/// through <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
/// and surfaces the raw <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TransactionResult}"/> —
/// interface choices have no typed <c>&lt;Choice&gt;Result</c> projection because the
/// implementing template (and therefore the produced contracts' shapes) is unknown
/// at the call site.
/// </summary>
public static class ITransferFactoryExtensions
{
    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>Archive</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<ITransferFactory> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return ExerciseCommand.ForInterface<ITransferFactory>(contractId, new ChoiceName("Archive"), DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the <c>Archive</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<TransactionResult>> ArchiveAsync(
        this ContractId<ITransferFactory> contractId,
        ILedgerWriter client,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        return client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken);
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>TransferFactory_PublicFetch</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand TransferFactory_PublicFetchCommand(
        this ContractId<ITransferFactory> contractId,
        TransferFactory_PublicFetch argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return ExerciseCommand.ForInterface<ITransferFactory>(contractId, new ChoiceName("TransferFactory_PublicFetch"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>TransferFactory_PublicFetch</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<TransactionResult>> TransferFactory_PublicFetchAsync(
        this ContractId<ITransferFactory> contractId,
        ILedgerWriter client,
        TransferFactory_PublicFetch argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.TransferFactory_PublicFetchCommand(argument);

        return client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken);
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>TransferFactory_Transfer</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand TransferFactory_TransferCommand(
        this ContractId<ITransferFactory> contractId,
        TransferFactory_Transfer argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return ExerciseCommand.ForInterface<ITransferFactory>(contractId, new ChoiceName("TransferFactory_Transfer"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>TransferFactory_Transfer</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<TransactionResult>> TransferFactory_TransferAsync(
        this ContractId<ITransferFactory> contractId,
        ILedgerWriter client,
        TransferFactory_Transfer argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.TransferFactory_TransferCommand(argument);

        return client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken);
    }
}
