// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Generated from Daml record Transfer
/// </summary>
public sealed record Transfer([property: DamlFieldAttribute("sender")] Splice.Api.Token.Holding.V2.Account Sender, [property: DamlFieldAttribute("receiver")] Splice.Api.Token.Holding.V2.Account Receiver, [property: DamlFieldAttribute("amount")] decimal Amount, [property: DamlFieldAttribute("instrumentId")] Splice.Api.Token.Holding.V2.InstrumentId InstrumentId, [property: DamlFieldAttribute("requestedAt")] DateTimeOffset RequestedAt, [property: DamlFieldAttribute("executeBefore")] DateTimeOffset ExecuteBefore, [property: DamlFieldAttribute("inputHoldingCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> InputHoldingCids, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("sender", Sender.ToRecord()),
        DamlField.Create("receiver", Receiver.ToRecord()),
        DamlField.Create("amount", new DamlNumeric(Amount)),
        DamlField.Create("instrumentId", InstrumentId.ToRecord()),
        DamlField.Create("requestedAt", new DamlTimestamp(RequestedAt)),
        DamlField.Create("executeBefore", new DamlTimestamp(ExecuteBefore)),
        DamlField.Create("inputHoldingCids", new DamlList(InputHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static Transfer FromRecord(DamlRecord record) => new Transfer(
        Sender: Splice.Api.Token.Holding.V2.Account.FromRecord(record.GetRequiredField("sender").As<DamlRecord>()),
        Receiver: Splice.Api.Token.Holding.V2.Account.FromRecord(record.GetRequiredField("receiver").As<DamlRecord>()),
        Amount: record.GetRequiredField("amount").As<DamlNumeric>().Value,
        InstrumentId: Splice.Api.Token.Holding.V2.InstrumentId.FromRecord(record.GetRequiredField("instrumentId").As<DamlRecord>()),
        RequestedAt: record.GetRequiredField("requestedAt").As<DamlTimestamp>().Value,
        ExecuteBefore: record.GetRequiredField("executeBefore").As<DamlTimestamp>().Value,
        InputHoldingCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("inputHoldingCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
