// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Generated from Daml record TransferInstructionResult_Output.TransferInstructionResult_Completed
/// </summary>
public sealed record TransferInstructionResult_Output_TransferInstructionResult_Completed([property: DamlFieldAttribute("receiverHoldingCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> ReceiverHoldingCids) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("receiverHoldingCids", new DamlList(ReceiverHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionResult_Output_TransferInstructionResult_Completed FromRecord(DamlRecord record) => new TransferInstructionResult_Output_TransferInstructionResult_Completed(
        ReceiverHoldingCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("receiverHoldingCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList()
    );

}
