// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Generated from Daml record TransferFactory_Transfer
/// </summary>
public sealed record TransferFactory_Transfer(
    [property: DamlFieldAttribute("transfer")] Transfer Transfer,
    [property: DamlFieldAttribute("actors")] IReadOnlyList<Party> Actors,
    [property: DamlFieldAttribute("extraArgs")] Splice.Api.Token.Metadata.V1.ExtraArgs ExtraArgs
) : IDamlRecord<TransferFactory_Transfer>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("transfer", Transfer.ToRecord()),
        DamlField.Create("actors", new DamlList(Actors.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("extraArgs", ExtraArgs.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferFactory_Transfer FromRecord(DamlRecord record) => new TransferFactory_Transfer(
        Transfer: Transfer.FromRecord(record.GetRequiredField("transfer").As<DamlRecord>()),
        Actors: (IReadOnlyList<Party>)record.GetRequiredField("actors").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList(),
        ExtraArgs: Splice.Api.Token.Metadata.V1.ExtraArgs.FromRecord(record.GetRequiredField("extraArgs").As<DamlRecord>())
    );

}
