// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Generated from Daml record TransferInstructionResult
/// </summary>
public sealed record TransferInstructionResult([property: DamlFieldAttribute("output")] TransferInstructionResult_Output Output, [property: DamlFieldAttribute("senderChangeCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> SenderChangeCids, [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("output", Output.ToVariant()),
        DamlField.Create("senderChangeCids", new DamlList(SenderChangeCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionResult FromRecord(DamlRecord record) => new TransferInstructionResult(
        Output: TransferInstructionResult_Output.FromVariant(record.GetRequiredField("output").As<DamlVariant>()),
        SenderChangeCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("senderChangeCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
