// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Phantom placeholder for the Daml interface <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c>.
/// Implements <see cref="ITemplate"/> so that <c>ContractId&lt;TransferFactory&gt;</c>
/// satisfies its <c>where T : ITemplate</c> constraint, but every static
/// metadata accessor throws — interface placeholders carry no template identity.
/// </summary>
/// <remarks>
/// Interface-instance choices need a concrete template to compile against, but the Daml
/// interface <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c> has none, so every static metadata accessor on this
/// placeholder throws by design. This does not affect interface choices, which the generated
/// extension methods exercise directly on <c>ContractId&lt;TransferFactory&gt;</c> — no coercion
/// needed. There is no supported way to recover a concrete <c>ContractId&lt;TConcrete&gt;</c>
/// from this placeholder; obtain one independently if concrete metadata is required.
/// </remarks>
public sealed record TransferFactory : ITemplate
{
    /// <summary>Always throws — the <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c> interface placeholder carries no template identity.</summary>
    /// <exception cref="System.InvalidOperationException">Thrown unconditionally — this placeholder carries no template identity to report.</exception>
    public static Identifier TemplateId =>
        throw new InvalidOperationException("'TransferFactory' is the C# placeholder for the Daml interface 'Splice.Api.Token.TransferInstructionV2:TransferFactory' and carries no template metadata. Exercise interface choices directly on ContractId<TransferFactory>; there is no supported coercion to a concrete ContractId<TConcrete>.");

    /// <summary>Always throws — the <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c> interface placeholder carries no package identity.</summary>
    /// <exception cref="System.InvalidOperationException">Thrown unconditionally — this placeholder carries no package identity to report.</exception>
    public static string PackageId =>
        throw new InvalidOperationException("'TransferFactory' is the C# placeholder for the Daml interface 'Splice.Api.Token.TransferInstructionV2:TransferFactory' and carries no template metadata. Exercise interface choices directly on ContractId<TransferFactory>; there is no supported coercion to a concrete ContractId<TConcrete>.");

    /// <summary>Always throws — the <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c> interface placeholder carries no package identity.</summary>
    /// <exception cref="System.InvalidOperationException">Thrown unconditionally — this placeholder carries no package identity to report.</exception>
    public static string PackageName =>
        throw new InvalidOperationException("'TransferFactory' is the C# placeholder for the Daml interface 'Splice.Api.Token.TransferInstructionV2:TransferFactory' and carries no template metadata. Exercise interface choices directly on ContractId<TransferFactory>; there is no supported coercion to a concrete ContractId<TConcrete>.");

    /// <summary>Always throws — the <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c> interface placeholder carries no package identity.</summary>
    /// <exception cref="System.InvalidOperationException">Thrown unconditionally — this placeholder carries no package identity to report.</exception>
    public static Version PackageVersion =>
        throw new InvalidOperationException("'TransferFactory' is the C# placeholder for the Daml interface 'Splice.Api.Token.TransferInstructionV2:TransferFactory' and carries no template metadata. Exercise interface choices directly on ContractId<TransferFactory>; there is no supported coercion to a concrete ContractId<TConcrete>.");

    /// <summary>Always throws — the <c>Splice.Api.Token.TransferInstructionV2:TransferFactory</c> interface placeholder carries no Daml type identity.</summary>
    /// <exception cref="System.InvalidOperationException">Thrown unconditionally — this placeholder carries no Daml type identity to report.</exception>
    public static DamlTypeDescriptor DamlTypeId =>
        throw new InvalidOperationException("'TransferFactory' is the C# placeholder for the Daml interface 'Splice.Api.Token.TransferInstructionV2:TransferFactory' and carries no template metadata. Exercise interface choices directly on ContractId<TransferFactory>; there is no supported coercion to a concrete ContractId<TConcrete>.");

    /// <summary>Converts this placeholder to an empty DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create();

    /// <summary>Creates an empty placeholder instance from a DamlRecord.</summary>
    public static TransferFactory FromRecord(DamlRecord record) => new TransferFactory();
}
