// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Api.Token.Transfer.Instruction.V2;

/// <summary>
/// Generated from Daml record TransferInstructionResult_Output.TransferInstructionResult_Pending
/// </summary>
public sealed record TransferInstructionResult_Output_TransferInstructionResult_Pending(
    [property: DamlFieldAttribute("transferInstructionCid")] ContractId<ITransferInstruction> TransferInstructionCid
) : IDamlRecord<TransferInstructionResult_Output_TransferInstructionResult_Pending>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("transferInstructionCid", TransferInstructionCid.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionResult_Output_TransferInstructionResult_Pending FromRecord(DamlRecord record) => new TransferInstructionResult_Output_TransferInstructionResult_Pending(
        TransferInstructionCid: new ContractId<ITransferInstruction>(record.GetRequiredField("transferInstructionCid").As<DamlContractId>().Value)
    );

}
