// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.AllocationRequestV2;

/// <summary>
/// Generated from Daml record AllocationRequest_Accept
/// </summary>
public sealed record AllocationRequest_Accept(
    IReadOnlyList<Party> Actors,
    global::Splice.Api.Token.MetadataV1.ExtraArgs ExtraArgs
) : IDamlRecord<AllocationRequest_Accept>
{
    private readonly IReadOnlyList<Party> _actors = DamlFieldCollections.Copy(Actors);

    /// <summary>The Daml field <c>actors</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("actors")]
    public IReadOnlyList<Party> Actors
    {
        get => _actors;
        init => _actors = DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>extraArgs</c>.</summary>
    [DamlFieldAttribute("extraArgs")]
    public global::Splice.Api.Token.MetadataV1.ExtraArgs ExtraArgs { get; init; } = ExtraArgs;

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(AllocationRequest_Accept? other) =>
        other is not null
        && DamlFieldCollections.Equal(Actors, other.Actors)
        && EqualityComparer<global::Splice.Api.Token.MetadataV1.ExtraArgs>.Default.Equals(ExtraArgs, other.ExtraArgs);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(DamlFieldCollections.Hash(Actors));
        hash.Add(ExtraArgs);
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("actors", new DamlList(Actors.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("extraArgs", ExtraArgs.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationRequest_Accept FromRecord(DamlRecord record) => new AllocationRequest_Accept(
        Actors: (IReadOnlyList<Party>)record.GetRequiredField("actors").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList(),
        ExtraArgs: global::Splice.Api.Token.MetadataV1.ExtraArgs.FromRecord(record.GetRequiredField("extraArgs").As<DamlRecord>())
    );

}
