// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Api.Token.AllocationRequestV2;

/// <summary>
/// Generated from Daml variant AllocationRequestAction
/// </summary>
public abstract record AllocationRequestAction : IDamlVariant<AllocationRequestAction>
{
    /// <summary>Gets the variant constructor name.</summary>
    public abstract string Tag { get; }

    /// <summary>Converts to a DamlVariant.</summary>
    public abstract DamlVariant ToVariant();

    /// <summary>Reconstructs an AllocationRequestAction by dispatching on the DamlVariant constructor tag.</summary>
    public static AllocationRequestAction FromVariant(DamlVariant variant) =>
        variant.Constructor switch
        {
            "ARA_Accept" => new ARA_Accept(),
            "ARA_Reject" => new ARA_Reject(),
            "ARA_Custom" => new ARA_Custom(AllocationRequestAction_ARA_Custom.FromRecord(variant.Value.As<DamlRecord>())),
            _ => throw new ArgumentOutOfRangeException(nameof(variant), variant.Constructor, "Unknown AllocationRequestAction constructor")
        };

    /// <summary>Decodes a Daml-LF JSON variant directly into a DamlVariant, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlVariant __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        var tag = global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadVariantTag(json, context);
        return tag switch
        {
            "ARA_Accept" => DamlVariant.Create("ARA_Accept", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "ARA_Reject" => DamlVariant.Create("ARA_Reject", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "ARA_Custom" => DamlVariant.Create("ARA_Custom", AllocationRequestAction_ARA_Custom.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            _ => throw global::Daml.Runtime.Serialization.DamlLfJsonDecoders.UnknownConstructor("variant constructor", tag, context, ExpectedConstructors)
        };
    }

    private static readonly string[] ExpectedConstructors = ["ARA_Accept", "ARA_Reject", "ARA_Custom"];

    /// <summary>ARA_Accept constructor (no arguments).</summary>
    public sealed record ARA_Accept() : AllocationRequestAction
    {
        /// <inheritdoc />
        public override string Tag => "ARA_Accept";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("ARA_Accept", DamlUnit.Instance);
    }

    /// <summary>ARA_Reject constructor (no arguments).</summary>
    public sealed record ARA_Reject() : AllocationRequestAction
    {
        /// <inheritdoc />
        public override string Tag => "ARA_Reject";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("ARA_Reject", DamlUnit.Instance);
    }

    /// <summary>ARA_Custom constructor.</summary>
    public sealed record ARA_Custom(AllocationRequestAction_ARA_Custom Value) : AllocationRequestAction
    {
        /// <inheritdoc />
        public override string Tag => "ARA_Custom";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("ARA_Custom", Value.ToRecord());
    }

}
