// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Api.Token.AllocationRequestV2;

/// <summary>
/// Generated from Daml interface Splice.Api.Token.AllocationRequestV2:AllocationRequest
/// </summary>
/// <remarks>
/// Instance properties mirror the fields of the interface view <see cref="AllocationRequestView"/>,
/// which implements this marker, so a view can be read through a marker-typed variable.
/// <c>==</c> between marker-typed variables compares by reference equality; view payloads
/// materialize as concrete <see cref="AllocationRequestView"/> values, whose record value equality
/// applies once concretely typed.
/// </remarks>
public interface IAllocationRequest : IDamlInterface, IHasView<AllocationRequestView>, IHasChoices<IAllocationRequest>
{
    /// <summary>Gets the interface identifier.</summary>
    static Identifier IDamlInterface.InterfaceId => InterfaceId;

    /// <summary>Gets the interface identifier.</summary>
    public static new Identifier InterfaceId { get; } = new("adc16315a8943a8433886694720a2a000ae84c2315c4414bd6d0db4d1660de9c", "Splice.Api.Token.AllocationRequestV2", "AllocationRequest");

    /// <summary>Gets the package ID.</summary>
    static string IDamlInterface.PackageId => "adc16315a8943a8433886694720a2a000ae84c2315c4414bd6d0db4d1660de9c";

    /// <summary>Gets the package name.</summary>
    static string IDamlInterface.PackageName => "splice-api-token-allocation-request-v2";

    /// <summary>Gets the package version.</summary>
    static Version IDamlInterface.PackageVersion => new(1, 0, 0);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    static DamlTypeDescriptor global::Daml.Runtime.IDamlType.DamlTypeId => new(new Identifier("adc16315a8943a8433886694720a2a000ae84c2315c4414bd6d0db4d1660de9c", "Splice.Api.Token.AllocationRequestV2", "AllocationRequest"), DamlTypeKind.Interface, "splice-api-token-allocation-request-v2");

    /// <summary>Gets the pure type witness pairing this marker with its view record <see cref="AllocationRequestView"/>; passing it to a generic method infers both type parameters from one argument.</summary>
    public static ViewDescriptor<IAllocationRequest, AllocationRequestView> View { get; } = new();

    /// <summary>Gets the originalRequestCid field of the interface view.</summary>
    ContractId<IAllocationRequest>? OriginalRequestCid { get; }

    /// <summary>Gets the settlement field of the interface view.</summary>
    global::Splice.Api.Token.AllocationV2.SettlementInfo Settlement { get; }

    /// <summary>Gets the allocations field of the interface view.</summary>
    IReadOnlyList<global::Splice.Api.Token.AllocationV2.AllocationSpecification> Allocations { get; }

    /// <summary>Gets the requestedAt field of the interface view.</summary>
    DateTimeOffset RequestedAt { get; }

    /// <summary>Gets the settleAt field of the interface view.</summary>
    DateTimeOffset? SettleAt { get; }

    /// <summary>Gets the availableActions field of the interface view.</summary>
    IReadOnlyDictionary<AllocationRequestAction, IReadOnlyList<IReadOnlyList<Party>>> AvailableActions { get; }

    /// <summary>Gets the meta field of the interface view.</summary>
    global::Splice.Api.Token.MetadataV1.Metadata Meta { get; }

    /// <summary>
    /// Exercise the AllocationRequest_Accept choice.
    /// </summary>
    public static Choice<IAllocationRequest, AllocationRequest_Accept, AllocationRequest_AcceptResult> ChoiceAllocationRequest_Accept { get; } = new()
    {
        Name = new ChoiceName("AllocationRequest_Accept"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Accept.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_AcceptResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AllocationRequest_Reject choice.
    /// </summary>
    public static Choice<IAllocationRequest, AllocationRequest_Reject, AllocationRequest_RejectResult> ChoiceAllocationRequest_Reject { get; } = new()
    {
        Name = new ChoiceName("AllocationRequest_Reject"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Reject.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_RejectResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the AllocationRequest_Withdraw choice.
    /// </summary>
    public static Choice<IAllocationRequest, AllocationRequest_Withdraw, AllocationRequest_WithdrawResult> ChoiceAllocationRequest_Withdraw { get; } = new()
    {
        Name = new ChoiceName("AllocationRequest_Withdraw"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ArgumentDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw.FromRecord(val.As<DamlRecord>()),
        ResultDecoder = val => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult.FromRecord(val.As<DamlRecord>()),
        ArgumentJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_Withdraw.__ReadDamlLfJson(json, context),
        ResultJsonReader = (json, context) => global::Splice.Api.Token.AllocationRequestV2.AllocationRequest_WithdrawResult.__ReadDamlLfJson(json, context),
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<IAllocationRequest, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlRecord.Create(),
        ArgumentDecoder = val => val is DamlRecord { Fields.Count: 0 } ? DamlUnit.Instance : throw new global::System.InvalidOperationException("Choice 'Archive' argument must decode to an empty record."),
        ResultDecoder = _ => DamlUnit.Instance,
        ArgumentJsonReader = (json, context) =>
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return DamlRecord.Create();
        },
        ResultJsonReader = (json, context) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadUnit(json, context),
    };

    /// <summary>Gets the choice descriptors declared by this type.</summary>
    static IReadOnlyList<IChoice> IHasChoices<IAllocationRequest>.Choices { get; } = [ChoiceAllocationRequest_Accept, ChoiceAllocationRequest_Reject, ChoiceAllocationRequest_Withdraw, ChoiceArchive];

}

/// <summary>
/// Static <c>&lt;Choice&gt;Async</c> extension methods for the <c>AllocationRequest</c> Daml interface.
/// One method per choice; each submits an interface-typed
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> built via
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand.For{TOwner}(global::Daml.Runtime.Contracts.ContractId{TOwner},global::Daml.Runtime.Commands.ChoiceName,global::Daml.Runtime.Data.DamlValue)"/>
/// through <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
/// and projects the committed transaction's matching exercise event through the choice
/// descriptor's <c>ResultDecoder</c>, surfacing a typed
/// <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TResult}"/> — the choice's own return
/// type, not the implementing template's. A decode failure after a successful commit
/// surfaces as <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TResult}.CommittedUndecodable"/>,
/// never as a resubmittable error.
/// </summary>
public static class IAllocationRequestExtensions
{
    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>AllocationRequest_Accept</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AllocationRequest_AcceptCommand(
        this ContractId<IAllocationRequest> contractId,
        AllocationRequest_Accept argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return ExerciseCommand.For<IAllocationRequest>(contractId, new ChoiceName("AllocationRequest_Accept"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>AllocationRequest_Accept</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceAllocationRequest_Accept.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AllocationRequest_AcceptResult>> AllocationRequest_AcceptAsync(
        this ContractId<IAllocationRequest> contractId,
        ILedgerWriter client,
        AllocationRequest_Accept argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AllocationRequest_AcceptCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAllocationRequest_AcceptResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>AllocationRequest_Reject</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AllocationRequest_RejectCommand(
        this ContractId<IAllocationRequest> contractId,
        AllocationRequest_Reject argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return ExerciseCommand.For<IAllocationRequest>(contractId, new ChoiceName("AllocationRequest_Reject"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>AllocationRequest_Reject</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceAllocationRequest_Reject.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AllocationRequest_RejectResult>> AllocationRequest_RejectAsync(
        this ContractId<IAllocationRequest> contractId,
        ILedgerWriter client,
        AllocationRequest_Reject argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AllocationRequest_RejectCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAllocationRequest_RejectResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>AllocationRequest_Withdraw</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AllocationRequest_WithdrawCommand(
        this ContractId<IAllocationRequest> contractId,
        AllocationRequest_Withdraw argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return ExerciseCommand.For<IAllocationRequest>(contractId, new ChoiceName("AllocationRequest_Withdraw"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>AllocationRequest_Withdraw</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and decoding the committed result through <c>ChoiceAllocationRequest_Withdraw.ResultDecoder</c>.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AllocationRequest_WithdrawResult>> AllocationRequest_WithdrawAsync(
        this ContractId<IAllocationRequest> contractId,
        ILedgerWriter client,
        AllocationRequest_Withdraw argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AllocationRequest_WithdrawCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAllocationRequest_WithdrawResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>Archive</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<IAllocationRequest> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return ExerciseCommand.For<IAllocationRequest>(contractId, new ChoiceName("Archive"), DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the <c>Archive</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.Extensions.SingleCommandExtensions.TrySubmitSingleAsync"/>
    /// and returning the committed result as the stdlib Unit singleton.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<Unit>> ArchiveAsync(
        this ContractId<IAllocationRequest> contractId,
        ILedgerWriter client,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static ExerciseOutcome<AllocationRequest_AcceptResult> ProjectAllocationRequest_AcceptResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (exercised.InterfaceId is { } interfaceId
                && string.Equals(exercised.ContractId, contractId, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.ModuleName, IAllocationRequest.InterfaceId.ModuleName, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.EntityName, IAllocationRequest.InterfaceId.EntityName, global::System.StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AllocationRequest_Accept", global::System.StringComparison.Ordinal))
            {
                try
                {
                    var decoded = IAllocationRequest.ChoiceAllocationRequest_Accept.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AllocationRequest_AcceptResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AllocationRequest_AcceptResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new global::System.InvalidOperationException(
            $"Submission succeeded but no 'AllocationRequest_Accept' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AllocationRequest_RejectResult> ProjectAllocationRequest_RejectResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (exercised.InterfaceId is { } interfaceId
                && string.Equals(exercised.ContractId, contractId, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.ModuleName, IAllocationRequest.InterfaceId.ModuleName, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.EntityName, IAllocationRequest.InterfaceId.EntityName, global::System.StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AllocationRequest_Reject", global::System.StringComparison.Ordinal))
            {
                try
                {
                    var decoded = IAllocationRequest.ChoiceAllocationRequest_Reject.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AllocationRequest_RejectResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AllocationRequest_RejectResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new global::System.InvalidOperationException(
            $"Submission succeeded but no 'AllocationRequest_Reject' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AllocationRequest_WithdrawResult> ProjectAllocationRequest_WithdrawResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (exercised.InterfaceId is { } interfaceId
                && string.Equals(exercised.ContractId, contractId, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.ModuleName, IAllocationRequest.InterfaceId.ModuleName, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.EntityName, IAllocationRequest.InterfaceId.EntityName, global::System.StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AllocationRequest_Withdraw", global::System.StringComparison.Ordinal))
            {
                try
                {
                    var decoded = IAllocationRequest.ChoiceAllocationRequest_Withdraw.ResultDecoder!(exercised.ExerciseResult);
                    return new ExerciseOutcome<AllocationRequest_WithdrawResult>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<AllocationRequest_WithdrawResult>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new global::System.InvalidOperationException(
            $"Submission succeeded but no 'AllocationRequest_Withdraw' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<Unit> ProjectArchiveResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (exercised.InterfaceId is { } interfaceId
                && string.Equals(exercised.ContractId, contractId, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.ModuleName, IAllocationRequest.InterfaceId.ModuleName, global::System.StringComparison.Ordinal)
                && string.Equals(interfaceId.EntityName, IAllocationRequest.InterfaceId.EntityName, global::System.StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "Archive", global::System.StringComparison.Ordinal))
            {
                try
                {
                    var decoded = Unit.Value;
                    return new ExerciseOutcome<Unit>.One(decoded);
                }
                catch (global::System.Exception ex) when (ex is not global::System.OperationCanceledException)
                {
                    return new ExerciseOutcome<Unit>.CommittedUndecodable(tx.UpdateId, ex.Message, ex);
                }
            }
        }

        throw new global::System.InvalidOperationException(
            $"Submission succeeded but no 'Archive' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
