// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.MetadataV1;

/// <summary>
/// Generated from Daml record AnyContractView
/// </summary>
public sealed record AnyContractView : IAnyContract, IDamlRecord<AnyContractView>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create();

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnyContractView FromRecord(DamlRecord record) => new AnyContractView();

}
