// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.MetadataV1;

/// <summary>
/// Generated from Daml variant AnyValue
/// </summary>
public abstract record AnyValue : IDamlVariant<AnyValue>
{
    /// <summary>Gets the variant constructor name.</summary>
    public abstract string Tag { get; }

    /// <summary>Converts to a DamlVariant.</summary>
    public abstract DamlVariant ToVariant();

    /// <summary>Reconstructs an AnyValue by dispatching on the DamlVariant constructor tag.</summary>
    public static AnyValue FromVariant(DamlVariant variant) =>
        variant.Constructor switch
        {
            "AV_Text" => new AV_Text(variant.Value.As<DamlText>().Value),
            "AV_Int" => new AV_Int(variant.Value.As<DamlInt64>().Value),
            "AV_Decimal" => new AV_Decimal(variant.Value.As<DamlNumeric>().Value),
            "AV_Bool" => new AV_Bool(variant.Value.As<DamlBool>().Value),
            "AV_Date" => new AV_Date(variant.Value.As<DamlDate>().Value),
            "AV_Time" => new AV_Time(variant.Value.As<DamlTimestamp>().Value),
            "AV_RelTime" => new AV_RelTime(RelTime.FromRecord(variant.Value.As<DamlRecord>())),
            "AV_Party" => new AV_Party(Party.FromDamlValue(variant.Value.As<DamlParty>())),
            "AV_ContractId" => new AV_ContractId(new ContractId<IAnyContract>(variant.Value.As<DamlContractId>().Value)),
            "AV_List" => new AV_List((IReadOnlyList<AnyValue>)variant.Value.As<DamlList>().Values.Select(x => AnyValue.FromVariant(x.As<DamlVariant>())).ToList()),
            "AV_Map" => new AV_Map((IReadOnlyDictionary<string, AnyValue>)variant.Value.As<DamlTextMap>().Values.ToDictionary(kv => kv.Key, kv => AnyValue.FromVariant(kv.Value.As<DamlVariant>()))),
            _ => throw new ArgumentOutOfRangeException(nameof(variant), variant.Constructor, "Unknown AnyValue constructor")
        };

    /// <summary>Decodes a Daml-LF JSON variant directly into a DamlVariant, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlVariant __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        var tag = global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadVariantTag(json, context);
        return tag switch
        {
            "AV_Text" => DamlVariant.Create("AV_Text", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadText(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_Int" => DamlVariant.Create("AV_Int", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadInt64(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_Decimal" => DamlVariant.Create("AV_Decimal", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadNumeric(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_Bool" => DamlVariant.Create("AV_Bool", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadBool(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_Date" => DamlVariant.Create("AV_Date", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadDate(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_Time" => DamlVariant.Create("AV_Time", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTimestamp(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_RelTime" => DamlVariant.Create("AV_RelTime", RelTime.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_Party" => DamlVariant.Create("AV_Party", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_ContractId" => DamlVariant.Create("AV_ContractId", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"))),
            "AV_List" => DamlVariant.Create("AV_List", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"), (__json0, __ctx0) => AnyValue.__ReadDamlLfJson(__json0, __ctx0))),
            "AV_Map" => DamlVariant.Create("AV_Map", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTextMap(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireVariantValue(json, context), context.Field("value"), (__json0, __ctx0) => AnyValue.__ReadDamlLfJson(__json0, __ctx0))),
            _ => throw global::Daml.Runtime.Serialization.DamlLfJsonDecoders.UnknownConstructor("variant constructor", tag, context, ExpectedConstructors)
        };
    }

    private static readonly string[] ExpectedConstructors = ["AV_Text", "AV_Int", "AV_Decimal", "AV_Bool", "AV_Date", "AV_Time", "AV_RelTime", "AV_Party", "AV_ContractId", "AV_List", "AV_Map"];

    /// <summary>AV_Text constructor.</summary>
    public sealed record AV_Text(string Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Text";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Text", new DamlText(Value));
    }

    /// <summary>AV_Int constructor.</summary>
    public sealed record AV_Int(long Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Int";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Int", new DamlInt64(Value));
    }

    /// <summary>AV_Decimal constructor.</summary>
    public sealed record AV_Decimal(decimal Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Decimal";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Decimal", new DamlNumeric(Value));
    }

    /// <summary>AV_Bool constructor.</summary>
    public sealed record AV_Bool(bool Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Bool";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Bool", new DamlBool(Value));
    }

    /// <summary>AV_Date constructor.</summary>
    public sealed record AV_Date(DateOnly Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Date";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Date", new DamlDate(Value));
    }

    /// <summary>AV_Time constructor.</summary>
    public sealed record AV_Time(DateTimeOffset Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Time";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Time", new DamlTimestamp(Value));
    }

    /// <summary>AV_RelTime constructor.</summary>
    public sealed record AV_RelTime(RelTime Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_RelTime";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_RelTime", Value.ToRecord());
    }

    /// <summary>AV_Party constructor.</summary>
    public sealed record AV_Party(Party Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_Party";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Party", Value.ToDamlValue());
    }

    /// <summary>AV_ContractId constructor.</summary>
    public sealed record AV_ContractId(ContractId<IAnyContract> Value) : AnyValue
    {
        /// <inheritdoc />
        public override string Tag => "AV_ContractId";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_ContractId", Value.ToDamlValue());
    }

    /// <summary>AV_List constructor.</summary>
    public sealed record AV_List(IReadOnlyList<AnyValue> Value) : AnyValue
    {
        private readonly IReadOnlyList<AnyValue> _value = DamlFieldCollections.Copy(Value);

        /// <summary>The payload the AV_List constructor carries. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
        public IReadOnlyList<AnyValue> Value
        {
            get => _value;
            init => _value = DamlFieldCollections.Copy(value);
        }

        /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
        /// <param name="other">The value to compare against.</param>
        /// <returns><c>true</c> when every member is equal.</returns>
        public bool Equals(AV_List? other) =>
            other is not null
            && base.Equals(other)
            && DamlFieldCollections.Equal(Value, other.Value);

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hash = new HashCode();
            hash.Add(base.GetHashCode());
            hash.Add(DamlFieldCollections.Hash(Value));
            return hash.ToHashCode();
        }

        /// <inheritdoc />
        public override string Tag => "AV_List";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_List", new DamlList(Value.Select(x => (DamlValue)x.ToVariant()).ToList()));
    }

    /// <summary>AV_Map constructor.</summary>
    public sealed record AV_Map(IReadOnlyDictionary<string, AnyValue> Value) : AnyValue
    {
        private readonly IReadOnlyDictionary<string, AnyValue> _value = DamlFieldCollections.Copy(Value);

        /// <summary>The payload the AV_Map constructor carries. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
        public IReadOnlyDictionary<string, AnyValue> Value
        {
            get => _value;
            init => _value = DamlFieldCollections.Copy(value);
        }

        /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
        /// <param name="other">The value to compare against.</param>
        /// <returns><c>true</c> when every member is equal.</returns>
        public bool Equals(AV_Map? other) =>
            other is not null
            && base.Equals(other)
            && DamlFieldCollections.Equal(Value, other.Value);

        /// <inheritdoc />
        public override int GetHashCode()
        {
            var hash = new HashCode();
            hash.Add(base.GetHashCode());
            hash.Add(DamlFieldCollections.Hash(Value));
            return hash.ToHashCode();
        }

        /// <inheritdoc />
        public override string Tag => "AV_Map";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AV_Map", new DamlTextMap(Value.ToDictionary(kv => kv.Key, kv => (DamlValue)kv.Value.ToVariant())));
    }

}
