// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.MetadataV1;

/// <summary>
/// Generated from Daml record ExtraArgs
/// </summary>
public sealed record ExtraArgs(
    [property: DamlFieldAttribute("context")] ChoiceContext Context,
    [property: DamlFieldAttribute("meta")] Metadata Meta
) : IDamlRecord<ExtraArgs>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("context", Context.ToRecord()),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static ExtraArgs FromRecord(DamlRecord record) => new ExtraArgs(
        Context: ChoiceContext.FromRecord(record.GetRequiredField("context").As<DamlRecord>()),
        Meta: Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
