// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.MetadataV1;

/// <summary>
/// Generated from Daml record ExtraArgs
/// </summary>
public sealed record ExtraArgs(
    [property: DamlFieldAttribute("context")] ChoiceContext Context,
    [property: DamlFieldAttribute("meta")] Metadata Meta
) : IDamlRecord<ExtraArgs>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("context", Context.ToRecord()),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static ExtraArgs FromRecord(DamlRecord record) => new ExtraArgs(
        Context: ChoiceContext.FromRecord(record.GetRequiredField("context").As<DamlRecord>()),
        Meta: Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("context", ChoiceContext.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "context"), context.Field("context"))),
            DamlField.Create("meta", Metadata.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "meta"), context.Field("meta")))
        );
    }

}
