// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Ans.AmuletConversionRateFeed;

/// <summary>
/// Generated from Daml record MarkerContext
/// </summary>
public sealed record MarkerContext(
    ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight> FeaturedAppRightCid,
    IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary> Beneficiaries
) : IDamlRecord<MarkerContext>
{
    /// <summary>The Daml field <c>featuredAppRightCid</c>.</summary>
    [DamlFieldAttribute("featuredAppRightCid")]
    public ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight> FeaturedAppRightCid { get; init; } = FeaturedAppRightCid;

    private readonly IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary> _beneficiaries = DamlFieldCollections.Copy(Beneficiaries);

    /// <summary>The Daml field <c>beneficiaries</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("beneficiaries")]
    public IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary> Beneficiaries
    {
        get => _beneficiaries;
        init => _beneficiaries = DamlFieldCollections.Copy(value);
    }

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(MarkerContext? other) =>
        other is not null
        && EqualityComparer<ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight>>.Default.Equals(FeaturedAppRightCid, other.FeaturedAppRightCid)
        && DamlFieldCollections.Equal(Beneficiaries, other.Beneficiaries);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(FeaturedAppRightCid);
        hash.Add(DamlFieldCollections.Hash(Beneficiaries));
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("featuredAppRightCid", FeaturedAppRightCid.ToDamlValue()),
        DamlField.Create("beneficiaries", new DamlList(Beneficiaries.Select(x => (DamlValue)x.ToRecord()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static MarkerContext FromRecord(DamlRecord record) => new MarkerContext(
        FeaturedAppRightCid: new ContractId<global::Splice.Api.FeaturedAppRightV1.IFeaturedAppRight>(record.GetRequiredField("featuredAppRightCid").As<DamlContractId>().Value),
        Beneficiaries: (IReadOnlyList<global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary>)record.GetRequiredField("beneficiaries").As<DamlList>().Values.Select(x => global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary.FromRecord(x.As<DamlRecord>())).ToList()
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("featuredAppRightCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "featuredAppRightCid"), context.Field("featuredAppRightCid"))),
            DamlField.Create("beneficiaries", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "beneficiaries"), context.Field("beneficiaries"), (__json0, __ctx0) => global::Splice.Api.FeaturedAppRightV1.AppRewardBeneficiary.__ReadDamlLfJson(__json0, __ctx0)))
        );
    }

}
