// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Holding.V1;

/// <summary>
/// Generated from Daml record InstrumentId
/// </summary>
public sealed record InstrumentId(Party Admin, string Id) : IDamlValue
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("admin", Admin.ToDamlValue()),
        DamlField.Create("id", new DamlText(Id))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static InstrumentId FromRecord(DamlRecord record) => new InstrumentId(
        Admin: Party.FromDamlValue(record.GetRequiredField("admin").As<DamlParty>()),
        Id: record.GetRequiredField("id").As<DamlText>().Value
    );

}
