// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Transfer.Events.V2;

/// <summary>
/// Generated from Daml record EventLog_HoldingsChange
/// </summary>
public sealed record EventLog_HoldingsChange(
    [property: DamlFieldAttribute("admin")] Party Admin,
    [property: DamlFieldAttribute("account")] Splice.Api.Token.Holding.V2.Account Account,
    [property: DamlFieldAttribute("inputHoldingCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> InputHoldingCids,
    [property: DamlFieldAttribute("transferLegSides")] IReadOnlyList<TransferLegSide> TransferLegSides,
    [property: DamlFieldAttribute("outputHoldingCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> OutputHoldingCids,
    [property: DamlFieldAttribute("observers")] IReadOnlyList<Party> Observers,
    [property: DamlFieldAttribute("extraArgs")] Splice.Api.Token.Metadata.V1.ExtraArgs ExtraArgs
) : IDamlRecord<EventLog_HoldingsChange>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("admin", Admin.ToDamlValue()),
        DamlField.Create("account", Account.ToRecord()),
        DamlField.Create("inputHoldingCids", new DamlList(InputHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("transferLegSides", new DamlList(TransferLegSides.Select(x => (DamlValue)x.ToRecord()).ToList())),
        DamlField.Create("outputHoldingCids", new DamlList(OutputHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("observers", new DamlList(Observers.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("extraArgs", ExtraArgs.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static EventLog_HoldingsChange FromRecord(DamlRecord record) => new EventLog_HoldingsChange(
        Admin: Party.FromDamlValue(record.GetRequiredField("admin").As<DamlParty>()),
        Account: Splice.Api.Token.Holding.V2.Account.FromRecord(record.GetRequiredField("account").As<DamlRecord>()),
        InputHoldingCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("inputHoldingCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        TransferLegSides: (IReadOnlyList<TransferLegSide>)record.GetRequiredField("transferLegSides").As<DamlList>().Values.Select(x => TransferLegSide.FromRecord(x.As<DamlRecord>())).ToList(),
        OutputHoldingCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("outputHoldingCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        Observers: (IReadOnlyList<Party>)record.GetRequiredField("observers").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList(),
        ExtraArgs: Splice.Api.Token.Metadata.V1.ExtraArgs.FromRecord(record.GetRequiredField("extraArgs").As<DamlRecord>())
    );

}
