// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Api.Token.Transfer.Events.V2;

/// <summary>
/// Generated from Daml interface Splice.Api.Token.TransferEventsV2:EventLog
/// </summary>
public interface IEventLog : IDamlInterface, IHasView<EventLogView>
{
    /// <summary>Gets the interface identifier.</summary>
    static Identifier IDamlInterface.InterfaceId => InterfaceId;

    /// <summary>Gets the interface identifier.</summary>
    public static new Identifier InterfaceId { get; } = new("5c1097a9bad0af4bcfe6d3fb0fe55112d3d11f18eae57ddfb14c20836fee226c", "Splice.Api.Token.TransferEventsV2", "EventLog");

    /// <summary>Gets the package ID.</summary>
    static string IDamlInterface.PackageId => "5c1097a9bad0af4bcfe6d3fb0fe55112d3d11f18eae57ddfb14c20836fee226c";

    /// <summary>Gets the package name.</summary>
    static string IDamlInterface.PackageName => "splice-api-token-transfer-events-v2";

    /// <summary>Gets the package version.</summary>
    static Version IDamlInterface.PackageVersion => new(1, 0, 0);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    static DamlTypeDescriptor global::Daml.Runtime.IDamlType.DamlTypeId => new(new Identifier("5c1097a9bad0af4bcfe6d3fb0fe55112d3d11f18eae57ddfb14c20836fee226c", "Splice.Api.Token.TransferEventsV2", "EventLog"), DamlTypeKind.Interface, "splice-api-token-transfer-events-v2");

    // Interface method Archive.
    // Choice Archive() -> DamlUnit
    // Interface method EventLog_HoldingsChange.
    // Choice EventLog_HoldingsChange(EventLog_HoldingsChange) -> EventLog_HoldingsChangeResult
}

/// <summary>
/// Static <c>&lt;Choice&gt;Async</c> extension methods for the <c>EventLog</c> Daml interface.
/// One method per choice; each submits an interface-typed
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> built via
/// <see cref="global::Daml.Runtime.Commands.ExerciseCommand.ForInterface{TInterface}(global::Daml.Runtime.Contracts.ContractId{TInterface},global::Daml.Runtime.Commands.ChoiceName,global::Daml.Runtime.Data.DamlValue)"/>
/// through <see cref="global::Daml.Ledger.Abstractions.ILedgerWriter.TrySubmitAndWaitForTransactionAsync"/>
/// and surfaces the raw <see cref="global::Daml.Runtime.Outcomes.ExerciseOutcome{TransactionResult}"/> —
/// interface choices have no typed <c>&lt;Choice&gt;Result</c> projection because the
/// implementing template (and therefore the produced contracts' shapes) is unknown
/// at the call site.
/// </summary>
public static class IEventLogExtensions
{
    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>Archive</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<IEventLog> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return ExerciseCommand.ForInterface<IEventLog>(contractId, new ChoiceName("Archive"), DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the <c>Archive</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.ILedgerWriter.TrySubmitAndWaitForTransactionAsync"/> and awaiting the outcome.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted. Pass the same id across a retry of a lost-but-accepted submission so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, enforced server-side; the default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<TransactionResult>> ArchiveAsync(
        this ContractId<IEventLog> contractId,
        ILedgerWriter client,
        Party actAs,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        var command = contractId.ArchiveCommand();

        var submission = CommandsSubmission.Single(command)
            .WithCommandId(commandId ?? new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        return await client.TrySubmitAndWaitForTransactionAsync(submission, actAs, timeout: timeout, cancellationToken: cancellationToken).ConfigureAwait(false);
    }

    /// <summary>
    /// Builds the interface-typed <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the <c>EventLog_HoldingsChange</c> choice on this contract id.
    /// The wire-level <c>template_id</c> slot carries the interface id — Canton's
    /// ledger API resolves the concrete implementing template at the participant.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand EventLog_HoldingsChangeCommand(
        this ContractId<IEventLog> contractId,
        EventLog_HoldingsChange argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return ExerciseCommand.ForInterface<IEventLog>(contractId, new ChoiceName("EventLog_HoldingsChange"), argument.ToRecord());
    }

    /// <summary>
    /// Exercises the <c>EventLog_HoldingsChange</c> interface choice on this contract id, submitting the
    /// resulting <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> through
    /// <see cref="global::Daml.Ledger.Abstractions.ILedgerWriter.TrySubmitAndWaitForTransactionAsync"/> and awaiting the outcome.
    /// </summary>
    /// <param name="contractId">The interface-typed contract id to exercise on.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted. Pass the same id across a retry of a lost-but-accepted submission so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, enforced server-side; the default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<TransactionResult>> EventLog_HoldingsChangeAsync(
        this ContractId<IEventLog> contractId,
        ILedgerWriter client,
        EventLog_HoldingsChange argument,
        Party actAs,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        var command = contractId.EventLog_HoldingsChangeCommand(argument);

        var submission = CommandsSubmission.Single(command)
            .WithCommandId(commandId ?? new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        return await client.TrySubmitAndWaitForTransactionAsync(submission, actAs, timeout: timeout, cancellationToken: cancellationToken).ConfigureAwait(false);
    }
}
