// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.AllocationInstructionV2;

/// <summary>
/// Generated from Daml record AllocationFactory_Allocate
/// </summary>
public sealed record AllocationFactory_Allocate(
    global::Splice.Api.Token.AllocationV2.SettlementInfo Settlement,
    global::Splice.Api.Token.AllocationV2.AllocationSpecification Allocation,
    DateTimeOffset RequestedAt,
    IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> InputHoldingCids,
    global::Splice.Api.Token.MetadataV1.ExtraArgs ExtraArgs,
    IReadOnlyList<Party> Actors
) : IDamlRecord<AllocationFactory_Allocate>
{
    /// <summary>The Daml field <c>settlement</c>.</summary>
    [DamlFieldAttribute("settlement")]
    public global::Splice.Api.Token.AllocationV2.SettlementInfo Settlement { get; init; } = Settlement;

    /// <summary>The Daml field <c>allocation</c>.</summary>
    [DamlFieldAttribute("allocation")]
    public global::Splice.Api.Token.AllocationV2.AllocationSpecification Allocation { get; init; } = Allocation;

    /// <summary>The Daml field <c>requestedAt</c>.</summary>
    [DamlFieldAttribute("requestedAt")]
    public DateTimeOffset RequestedAt { get; init; } = RequestedAt;

    private readonly IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> _inputHoldingCids = DamlFieldCollections.Copy(InputHoldingCids);

    /// <summary>The Daml field <c>inputHoldingCids</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("inputHoldingCids")]
    public IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> InputHoldingCids
    {
        get => _inputHoldingCids;
        init => _inputHoldingCids = DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>extraArgs</c>.</summary>
    [DamlFieldAttribute("extraArgs")]
    public global::Splice.Api.Token.MetadataV1.ExtraArgs ExtraArgs { get; init; } = ExtraArgs;

    private readonly IReadOnlyList<Party> _actors = DamlFieldCollections.Copy(Actors);

    /// <summary>The Daml field <c>actors</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("actors")]
    public IReadOnlyList<Party> Actors
    {
        get => _actors;
        init => _actors = DamlFieldCollections.Copy(value);
    }

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(AllocationFactory_Allocate? other) =>
        other is not null
        && EqualityComparer<global::Splice.Api.Token.AllocationV2.SettlementInfo>.Default.Equals(Settlement, other.Settlement)
        && EqualityComparer<global::Splice.Api.Token.AllocationV2.AllocationSpecification>.Default.Equals(Allocation, other.Allocation)
        && EqualityComparer<DateTimeOffset>.Default.Equals(RequestedAt, other.RequestedAt)
        && DamlFieldCollections.Equal(InputHoldingCids, other.InputHoldingCids)
        && EqualityComparer<global::Splice.Api.Token.MetadataV1.ExtraArgs>.Default.Equals(ExtraArgs, other.ExtraArgs)
        && DamlFieldCollections.Equal(Actors, other.Actors);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(Settlement);
        hash.Add(Allocation);
        hash.Add(RequestedAt);
        hash.Add(DamlFieldCollections.Hash(InputHoldingCids));
        hash.Add(ExtraArgs);
        hash.Add(DamlFieldCollections.Hash(Actors));
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("settlement", Settlement.ToRecord()),
        DamlField.Create("allocation", Allocation.ToRecord()),
        DamlField.Create("requestedAt", new DamlTimestamp(RequestedAt)),
        DamlField.Create("inputHoldingCids", new DamlList(InputHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("extraArgs", ExtraArgs.ToRecord()),
        DamlField.Create("actors", new DamlList(Actors.Select(x => (DamlValue)x.ToDamlValue()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationFactory_Allocate FromRecord(DamlRecord record) => new AllocationFactory_Allocate(
        Settlement: global::Splice.Api.Token.AllocationV2.SettlementInfo.FromRecord(record.GetRequiredField("settlement").As<DamlRecord>()),
        Allocation: global::Splice.Api.Token.AllocationV2.AllocationSpecification.FromRecord(record.GetRequiredField("allocation").As<DamlRecord>()),
        RequestedAt: record.GetRequiredField("requestedAt").As<DamlTimestamp>().Value,
        InputHoldingCids: (IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>>)record.GetRequiredField("inputHoldingCids").As<DamlList>().Values.Select(x => new ContractId<global::Splice.Api.Token.HoldingV2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        ExtraArgs: global::Splice.Api.Token.MetadataV1.ExtraArgs.FromRecord(record.GetRequiredField("extraArgs").As<DamlRecord>()),
        Actors: (IReadOnlyList<Party>)record.GetRequiredField("actors").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList()
    );

}
