// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using static Daml.Runtime.Contracts.TemplateExtensions;

namespace Splice.Test.Token.V1;

/// <summary>
/// Provides fully qualified contract identifiers for all templates in this package.
/// These identifiers can be used for PQS queries.
/// </summary>
public static class ContractIdentifiers
{
    /// <summary>
    /// Gets the fully qualified template identifier for Token contracts.
    /// Format: {packageName}:Splice.Testing.Tokens.TestTokenV1:Token
    /// </summary>
    public static string Token { get; } = GetTemplateId<Token>();

    /// <summary>
    /// Gets the fully qualified template identifier for TokenAllocation contracts.
    /// Format: {packageName}:Splice.Testing.Tokens.TestTokenV1:TokenAllocation
    /// </summary>
    public static string TokenAllocation { get; } = GetTemplateId<TokenAllocation>();

    /// <summary>
    /// Gets the fully qualified template identifier for TokenRules contracts.
    /// Format: {packageName}:Splice.Testing.Tokens.TestTokenV1:TokenRules
    /// </summary>
    public static string TokenRules { get; } = GetTemplateId<TokenRules>();

    /// <summary>
    /// Gets the fully qualified template identifier for TokenTransferOffer contracts.
    /// Format: {packageName}:Splice.Testing.Tokens.TestTokenV1:TokenTransferOffer
    /// </summary>
    public static string TokenTransferOffer { get; } = GetTemplateId<TokenTransferOffer>();
}
