// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using static Daml.Runtime.Contracts.TemplateExtensions;

namespace CollisionB;

/// <summary>
/// Provides fully qualified contract identifiers for all templates in this module.
/// These identifiers can be used for PQS queries.
/// </summary>
public static class ContractIdentifiers
{
    /// <summary>
    /// Gets the fully qualified template identifier for Offer contracts.
    /// Format: {packageName}:CollisionB:Offer
    /// </summary>
    public static string Offer { get; } = GetTemplateId<Offer>();
}
