// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace CollisionA;

public sealed partial record Agreement
{
    /// <summary>
    /// Choice argument type for Retag.
    /// </summary>
    public sealed record Retag(
        [property: DamlFieldAttribute("newOperator")] Party NewOperator
    ) : IDamlRecord<Retag>
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("newOperator", NewOperator.ToDamlValue())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static Retag FromRecord(DamlRecord record) => new Retag(
            NewOperator: Party.FromDamlValue(record.GetRequiredField("newOperator").As<DamlParty>())
        );

        /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
        {
            global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
            return DamlRecord.Create(
                DamlField.Create("newOperator", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "newOperator"), context.Field("newOperator")))
            );
        }

    }
}
