// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using static Daml.Runtime.Contracts.TemplateExtensions;

namespace CollisionA;

/// <summary>
/// Provides fully qualified contract identifiers for all templates in this module.
/// These identifiers can be used for PQS queries.
/// </summary>
public static class ContractIdentifiers
{
    /// <summary>
    /// Gets the fully qualified template identifier for Agreement contracts.
    /// Format: {packageName}:CollisionA:Agreement
    /// </summary>
    public static string Agreement { get; } = GetTemplateId<Agreement>();
}
