// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using static Daml.Runtime.Contracts.TemplateExtensions;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Provides fully qualified contract identifiers for all templates in this package.
/// These identifiers can be used for PQS queries.
/// </summary>
public static class ContractIdentifiers
{
    /// <summary>
    /// Gets the fully qualified template identifier for AnsEntry contracts.
    /// Format: {packageName}:Splice.Ans:AnsEntry
    /// </summary>
    public static string AnsEntry { get; } = GetTemplateId<AnsEntry>();

    /// <summary>
    /// Gets the fully qualified template identifier for AnsEntryContext contracts.
    /// Format: {packageName}:Splice.Ans:AnsEntryContext
    /// </summary>
    public static string AnsEntryContext { get; } = GetTemplateId<AnsEntryContext>();

    /// <summary>
    /// Gets the fully qualified template identifier for AnsRules contracts.
    /// Format: {packageName}:Splice.Ans:AnsRules
    /// </summary>
    public static string AnsRules { get; } = GetTemplateId<AnsRules>();

    /// <summary>
    /// Gets the fully qualified template identifier for AmuletConversionRateFeed contracts.
    /// Format: {packageName}:Splice.Ans.AmuletConversionRateFeed:AmuletConversionRateFeed
    /// </summary>
    public static string AmuletConversionRateFeed { get; } = GetTemplateId<AmuletConversionRateFeed>();
}
