// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.Allocation.Instruction.V2;

/// <summary>
/// Generated from Daml record AllocationFactory_Allocate
/// </summary>
public sealed record AllocationFactory_Allocate(
    [property: DamlFieldAttribute("settlement")] Splice.Api.Token.Allocation.V2.SettlementInfo Settlement,
    [property: DamlFieldAttribute("allocation")] Splice.Api.Token.Allocation.V2.AllocationSpecification Allocation,
    [property: DamlFieldAttribute("requestedAt")] DateTimeOffset RequestedAt,
    [property: DamlFieldAttribute("inputHoldingCids")] IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>> InputHoldingCids,
    [property: DamlFieldAttribute("extraArgs")] Splice.Api.Token.Metadata.V1.ExtraArgs ExtraArgs,
    [property: DamlFieldAttribute("actors")] IReadOnlyList<Party> Actors
) : IDamlRecord<AllocationFactory_Allocate>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("settlement", Settlement.ToRecord()),
        DamlField.Create("allocation", Allocation.ToRecord()),
        DamlField.Create("requestedAt", new DamlTimestamp(RequestedAt)),
        DamlField.Create("inputHoldingCids", new DamlList(InputHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("extraArgs", ExtraArgs.ToRecord()),
        DamlField.Create("actors", new DamlList(Actors.Select(x => (DamlValue)x.ToDamlValue()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationFactory_Allocate FromRecord(DamlRecord record) => new AllocationFactory_Allocate(
        Settlement: Splice.Api.Token.Allocation.V2.SettlementInfo.FromRecord(record.GetRequiredField("settlement").As<DamlRecord>()),
        Allocation: Splice.Api.Token.Allocation.V2.AllocationSpecification.FromRecord(record.GetRequiredField("allocation").As<DamlRecord>()),
        RequestedAt: record.GetRequiredField("requestedAt").As<DamlTimestamp>().Value,
        InputHoldingCids: (IReadOnlyList<ContractId<Splice.Api.Token.Holding.V2.IHolding>>)record.GetRequiredField("inputHoldingCids").As<DamlList>().Values.Select(x => new ContractId<Splice.Api.Token.Holding.V2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        ExtraArgs: Splice.Api.Token.Metadata.V1.ExtraArgs.FromRecord(record.GetRequiredField("extraArgs").As<DamlRecord>()),
        Actors: (IReadOnlyList<Party>)record.GetRequiredField("actors").As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList()
    );

}
