// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.Instruction.V2;

/// <summary>
/// Generated from Daml record AllocationInstructionResult_Output.AllocationInstructionResult_Completed
/// </summary>
public sealed record AllocationInstructionResult_Output_AllocationInstructionResult_Completed(
    [property: DamlFieldAttribute("allocationCid")] ContractId<Splice.Api.Token.Allocation.V2.IAllocation> AllocationCid
) : IDamlRecord<AllocationInstructionResult_Output_AllocationInstructionResult_Completed>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("allocationCid", AllocationCid.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationInstructionResult_Output_AllocationInstructionResult_Completed FromRecord(DamlRecord record) => new AllocationInstructionResult_Output_AllocationInstructionResult_Completed(
        AllocationCid: new ContractId<Splice.Api.Token.Allocation.V2.IAllocation>(record.GetRequiredField("allocationCid").As<DamlContractId>().Value)
    );

}
