// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Api.Token.Allocation.Instruction.V2;

/// <summary>
/// Generated from Daml variant AllocationInstructionAction
/// </summary>
public abstract record AllocationInstructionAction : IDamlVariant
{
    /// <summary>Gets the variant constructor name.</summary>
    public abstract string Tag { get; }

    /// <summary>Converts to a DamlVariant.</summary>
    public abstract DamlVariant ToVariant();

    /// <summary>Reconstructs an AllocationInstructionAction by dispatching on the DamlVariant constructor tag.</summary>
    public static AllocationInstructionAction FromVariant(DamlVariant variant) =>
        variant.Constructor switch
        {
            "AIA_Withdraw" => new AIA_Withdraw(),
            "AIA_Accept" => new AIA_Accept(),
            "AIA_Custom" => new AIA_Custom(AllocationInstructionAction_AIA_Custom.FromRecord(variant.Value.As<DamlRecord>())),
            _ => throw new ArgumentOutOfRangeException(nameof(variant), variant.Constructor, "Unknown AllocationInstructionAction constructor")
        };

    /// <summary>AIA_Withdraw constructor (no arguments).</summary>
    public sealed record AIA_Withdraw() : AllocationInstructionAction
    {
        /// <inheritdoc />
        public override string Tag => "AIA_Withdraw";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AIA_Withdraw", DamlUnit.Instance);
    }

    /// <summary>AIA_Accept constructor (no arguments).</summary>
    public sealed record AIA_Accept() : AllocationInstructionAction
    {
        /// <inheritdoc />
        public override string Tag => "AIA_Accept";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AIA_Accept", DamlUnit.Instance);
    }

    /// <summary>AIA_Custom constructor.</summary>
    public sealed record AIA_Custom(AllocationInstructionAction_AIA_Custom Value) : AllocationInstructionAction
    {
        /// <inheritdoc />
        public override string Tag => "AIA_Custom";

        /// <inheritdoc />
        public override DamlVariant ToVariant() => DamlVariant.Create("AIA_Custom", Value.ToRecord());
    }

}
