// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.Instruction.V2;

/// <summary>
/// Generated from Daml record AllocationInstructionAction.AIA_Custom
/// </summary>
public sealed record AllocationInstructionAction_AIA_Custom(
    [property: DamlFieldAttribute("id")] string Id
) : IDamlRecord<AllocationInstructionAction_AIA_Custom>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("id", new DamlText(Id))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationInstructionAction_AIA_Custom FromRecord(DamlRecord record) => new AllocationInstructionAction_AIA_Custom(
        Id: record.GetRequiredField("id").As<DamlText>().Value
    );

}
