// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.Request.V2;

/// <summary>
/// Generated from Daml record AllocationRequestAction.ARA_Custom
/// </summary>
public sealed record AllocationRequestAction_ARA_Custom([property: DamlFieldAttribute("id")] string Id) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("id", new DamlText(Id))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationRequestAction_ARA_Custom FromRecord(DamlRecord record) => new AllocationRequestAction_ARA_Custom(
        Id: record.GetRequiredField("id").As<DamlText>().Value
    );

}
