// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Api.Token.Allocation.Request.V2;

/// <summary>
/// Generated from Daml record AllocationRequest_RejectResult
/// </summary>
public sealed record AllocationRequest_RejectResult(
    [property: DamlFieldAttribute("meta")] Splice.Api.Token.Metadata.V1.Metadata Meta
) : IDamlRecord<AllocationRequest_RejectResult>
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AllocationRequest_RejectResult FromRecord(DamlRecord record) => new AllocationRequest_RejectResult(
        Meta: Splice.Api.Token.Metadata.V1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
