// Copyright 2026 Peaceful Studio OÜ
// SPDX-License-Identifier: Apache-2.0

using System.Text;
using RuntimeNamespaces = Daml.Runtime.RuntimeNamespaces;

namespace Daml.Codegen.CSharp.CodeGen;

public sealed partial class CSharpCodeGenerator
{
    private string EmitFile(string moduleNamespace, Action<IndentWriter> writeBody)
    {
        var bodySb = new StringBuilder();
        var indent = new IndentWriter(bodySb);

        if (options.UseFileScopedNamespaces)
        {
            indent.AppendLine($"namespace {moduleNamespace};");
            indent.AppendLine();
        }
        else
        {
            indent.AppendLine($"namespace {moduleNamespace}");
            indent.AppendLine("{");
            indent.Indent();
        }

        writeBody(indent);

        if (!options.UseFileScopedNamespaces)
        {
            indent.Dedent();
            indent.AppendLine("}");
        }

        return BuildFileContent(indent, bodySb);
    }

    private void WriteFileHeader(IndentWriter indent)
    {
        indent.AppendLine("// <auto-generated>");
        indent.AppendLine("// This code was generated by daml-codegen-csharp.");
        indent.AppendLine("// Do not edit this file manually.");
        indent.AppendLine("// </auto-generated>");
        indent.AppendLine();

        if (options.EnableNullableReferenceTypes)
        {
            indent.AppendLine("#nullable enable");
            indent.AppendLine();
        }
    }

    private static void WriteTrackedUsings(IndentWriter headerIndent, IndentWriter bodyIndent)
    {
        foreach (var ns in bodyIndent.RequiredUsings)
        {
            headerIndent.AppendLine($"using {ns};");
        }
        headerIndent.AppendLine();
    }

    private string BuildFileContent(IndentWriter bodyIndent, StringBuilder bodySb)
    {
        var headerSb = new StringBuilder();
        var headerIndent = new IndentWriter(headerSb);
        WriteFileHeader(headerIndent);
        WriteTrackedUsings(headerIndent, bodyIndent);
        headerSb.Append(bodySb);
        return headerSb.ToString();
    }

    private void RequireCommonNamespaces(IndentWriter indent)
    {
        indent.Require(RuntimeNamespaces.Data);
    }
}
