using System.Text;
using Daml.Codegen.CSharp.DarReader;

namespace Daml.Codegen.CSharp.CodeGen;

/// <summary>
/// Generates .csproj project files for Daml-generated C# code.
/// </summary>
public sealed class ProjectFileGenerator
{
    private readonly CodeGenOptions _options;

    public ProjectFileGenerator(CodeGenOptions options)
    {
        _options = options;
    }

    /// <summary>
    /// Generates a .csproj file for the given package.
    /// </summary>
    /// <param name="package">The main package being generated.</param>
    /// <param name="externalReferences">
    /// Other DAR-level packages whose types are referenced by the generated code.
    /// Each becomes a NuGet PackageReference in the generated csproj.
    /// </param>
    public GeneratedFile GenerateProjectFile(DamlPackage package, IReadOnlyList<DamlPackage>? externalReferences = null)
    {
        var packageName = SanitizePackageName(package.Name);
        var projectFileName = $"{packageName}.csproj";

        var content = GenerateProjectFileContent(package, packageName, externalReferences ?? []);

        return new GeneratedFile(projectFileName, content);
    }

    private string GenerateProjectFileContent(DamlPackage package, string packageName, IReadOnlyList<DamlPackage> externalReferences)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        sb.AppendLine();
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine($"    <TargetFramework>{_options.TargetFramework}</TargetFramework>");
        sb.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");

        if (_options.EnableNullableReferenceTypes)
        {
            sb.AppendLine("    <Nullable>enable</Nullable>");
        }

        sb.AppendLine($"    <PackageId>{packageName}</PackageId>");
        sb.AppendLine($"    <Version>{package.Version}</Version>");
        sb.AppendLine($"    <Description>C# bindings for Daml package {package.Name}</Description>");
        sb.AppendLine("    <Authors>Generated by Daml.Codegen.CSharp</Authors>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine();

        // Add package references
        sb.AppendLine("  <ItemGroup>");

        // Runtime package reference
        var runtimeVersion = _options.RuntimePackageVersion ?? "*";
        sb.AppendLine($"    <PackageReference Include=\"Daml.Runtime\" Version=\"{runtimeVersion}\" />");

        // Add cross-DAR package references for any external types referenced in generated code.
        // Stdlib packages (daml-prim/daml-stdlib) are filtered out by the generator before this
        // point — those types come from Daml.Runtime.Stdlib.
        foreach (var dep in externalReferences.OrderBy(p => p.Name, StringComparer.Ordinal))
        {
            var depPackageName = SanitizePackageName(dep.Name);
            sb.AppendLine($"    <PackageReference Include=\"{depPackageName}\" Version=\"{dep.Version}\" />");
        }

        sb.AppendLine("  </ItemGroup>");

        sb.AppendLine();
        sb.AppendLine("</Project>");

        return sb.ToString();
    }

    /// <summary>
    /// Sanitizes a Daml package name to be a valid .NET package/project name.
    /// Converts to PascalCase and joins with dots (e.g., "cats-markets" -> "Cats.Markets").
    /// </summary>
    private static string SanitizePackageName(string name)
    {
        // Split on hyphens and underscores, convert each part to PascalCase
        var parts = name.Split('-', '_')
            .Select(ToPascalCase)
            .Select(SanitizeIdentifier);
        return string.Join(".", parts);
    }

    private static string ToPascalCase(string s)
    {
        if (string.IsNullOrEmpty(s))
        {
            return s;
        }

        // Capitalize first letter
        return char.ToUpperInvariant(s[0]) + s[1..];
    }

    private static string SanitizeIdentifier(string name)
    {
        // Replace invalid characters with underscores
        var sanitized = string.Concat(name.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_'));

        // Ensure it doesn't start with a number
        if (sanitized.Length > 0 && char.IsDigit(sanitized[0]))
        {
            sanitized = "_" + sanitized;
        }

        return sanitized;
    }
}
