using System.Text;
using Daml.Codegen.CSharp.DarReader;

namespace Daml.Codegen.CSharp.CodeGen;

/// <summary>
/// Generates .csproj project files for Daml-generated C# code.
/// </summary>
public sealed class ProjectFileGenerator
{
    private readonly CodeGenOptions _options;

    public ProjectFileGenerator(CodeGenOptions options)
    {
        _options = options;
    }

    /// <summary>
    /// Generates a .csproj file for the given package.
    /// </summary>
    public GeneratedFile GenerateProjectFile(DamlPackage package)
    {
        var packageName = SanitizePackageName(package.Name);
        var projectFileName = $"{packageName}.csproj";

        var content = GenerateProjectFileContent(package, packageName);

        return new GeneratedFile(projectFileName, content);
    }

    private string GenerateProjectFileContent(DamlPackage package, string packageName)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<Project Sdk=\"Microsoft.NET.Sdk\">");
        sb.AppendLine();
        sb.AppendLine("  <PropertyGroup>");
        sb.AppendLine($"    <TargetFramework>{_options.TargetFramework}</TargetFramework>");
        sb.AppendLine("    <ImplicitUsings>enable</ImplicitUsings>");

        if (_options.EnableNullableReferenceTypes)
        {
            sb.AppendLine("    <Nullable>enable</Nullable>");
        }

        sb.AppendLine($"    <PackageId>{packageName}</PackageId>");
        sb.AppendLine($"    <Version>{package.Version}</Version>");
        sb.AppendLine($"    <Description>C# bindings for Daml package {package.Name}</Description>");
        sb.AppendLine("    <Authors>Generated by Daml.Codegen.CSharp</Authors>");
        sb.AppendLine("  </PropertyGroup>");
        sb.AppendLine();

        // Add package references
        sb.AppendLine("  <ItemGroup>");

        // Runtime package reference
        var runtimeVersion = _options.RuntimePackageVersion ?? "*";
        sb.AppendLine($"    <PackageReference Include=\"Daml.Codegen.CSharp.Runtime\" Version=\"{runtimeVersion}\" />");

        sb.AppendLine("  </ItemGroup>");

        // Add project references for dependencies if they exist
        if (package.DependencyReferences.Count > 0)
        {
            sb.AppendLine();
            sb.AppendLine("  <!-- Dependency package references -->");
            sb.AppendLine("  <!-- These can be changed to NuGet PackageReferences once packages are published -->");
            sb.AppendLine("  <ItemGroup>");

            foreach (var depRef in package.DependencyReferences)
            {
                if (depRef.Name != null)
                {
                    var depPackageName = SanitizePackageName(depRef.Name);
                    var depVersion = depRef.Version?.ToString() ?? "*";
                    sb.AppendLine($"    <!-- Package: {depRef.Name} ({depRef.PackageId[..Math.Min(16, depRef.PackageId.Length)]}) -->");
                    sb.AppendLine($"    <PackageReference Include=\"{depPackageName}\" Version=\"{depVersion}\" />");
                }
                else
                {
                    // Unknown dependency - add as comment
                    sb.AppendLine($"    <!-- Unknown dependency: {depRef.PackageId} -->");
                }
            }

            sb.AppendLine("  </ItemGroup>");
        }

        sb.AppendLine();
        sb.AppendLine("</Project>");

        return sb.ToString();
    }

    /// <summary>
    /// Sanitizes a Daml package name to be a valid .NET package/project name.
    /// </summary>
    private static string SanitizePackageName(string name)
    {
        // Replace hyphens with dots (common convention)
        // Also handle any other invalid characters
        var sanitized = name.Replace('-', '.');

        // Ensure it doesn't start with a number
        if (sanitized.Length > 0 && char.IsDigit(sanitized[0]))
        {
            sanitized = "_" + sanitized;
        }

        return sanitized;
    }
}
