// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.TransferInstructionV2;

/// <summary>
/// Generated from Daml record TransferInstructionResult_Output.TransferInstructionResult_Completed
/// </summary>
public sealed record TransferInstructionResult_Output_TransferInstructionResult_Completed(
    IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> ReceiverHoldingCids
) : IDamlRecord<TransferInstructionResult_Output_TransferInstructionResult_Completed>
{
    private readonly IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> _receiverHoldingCids = DamlFieldCollections.Copy(ReceiverHoldingCids);

    /// <summary>The Daml field <c>receiverHoldingCids</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("receiverHoldingCids")]
    public IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> ReceiverHoldingCids
    {
        get => _receiverHoldingCids;
        init => _receiverHoldingCids = DamlFieldCollections.Copy(value);
    }

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(TransferInstructionResult_Output_TransferInstructionResult_Completed? other) =>
        other is not null
        && DamlFieldCollections.Equal(ReceiverHoldingCids, other.ReceiverHoldingCids);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(DamlFieldCollections.Hash(ReceiverHoldingCids));
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("receiverHoldingCids", new DamlList(ReceiverHoldingCids.Select(x => (DamlValue)x.ToDamlValue()).ToList()))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionResult_Output_TransferInstructionResult_Completed FromRecord(DamlRecord record) => new TransferInstructionResult_Output_TransferInstructionResult_Completed(
        ReceiverHoldingCids: (IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>>)record.GetRequiredField("receiverHoldingCids").As<DamlList>().Values.Select(x => new ContractId<global::Splice.Api.Token.HoldingV2.IHolding>(x.As<DamlContractId>().Value)).ToList()
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("receiverHoldingCids", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "receiverHoldingCids"), context.Field("receiverHoldingCids"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(__json0, __ctx0)))
        );
    }

}
