// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.TransferInstructionV2;

/// <summary>
/// Generated from Daml record TransferInstructionView
/// </summary>
public sealed record TransferInstructionView(
    ContractId<ITransferInstruction>? OriginalInstructionCid,
    Transfer Transfer,
    DateTimeOffset? ExpiresAt,
    IReadOnlyDictionary<TransferInstructionAction, IReadOnlyList<IReadOnlyList<Party>>> AvailableActions,
    global::Splice.Api.Token.MetadataV1.Metadata Meta
) : ITransferInstruction, IDamlRecord<TransferInstructionView>
{
    /// <summary>The Daml field <c>originalInstructionCid</c>.</summary>
    [DamlFieldAttribute("originalInstructionCid")]
    public ContractId<ITransferInstruction>? OriginalInstructionCid { get; init; } = OriginalInstructionCid;

    /// <summary>The Daml field <c>transfer</c>.</summary>
    [DamlFieldAttribute("transfer")]
    public Transfer Transfer { get; init; } = Transfer;

    /// <summary>The Daml field <c>expiresAt</c>.</summary>
    [DamlFieldAttribute("expiresAt")]
    public DateTimeOffset? ExpiresAt { get; init; } = ExpiresAt;

    private readonly IReadOnlyDictionary<TransferInstructionAction, IReadOnlyList<IReadOnlyList<Party>>> _availableActions = DamlFieldCollections.Copy(AvailableActions);

    /// <summary>The Daml field <c>availableActions</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("availableActions")]
    public IReadOnlyDictionary<TransferInstructionAction, IReadOnlyList<IReadOnlyList<Party>>> AvailableActions
    {
        get => _availableActions;
        init => _availableActions = DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>meta</c>.</summary>
    [DamlFieldAttribute("meta")]
    public global::Splice.Api.Token.MetadataV1.Metadata Meta { get; init; } = Meta;

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(TransferInstructionView? other) =>
        other is not null
        && EqualityComparer<ContractId<ITransferInstruction>?>.Default.Equals(OriginalInstructionCid, other.OriginalInstructionCid)
        && EqualityComparer<Transfer>.Default.Equals(Transfer, other.Transfer)
        && EqualityComparer<DateTimeOffset?>.Default.Equals(ExpiresAt, other.ExpiresAt)
        && DamlFieldCollections.Equal(AvailableActions, other.AvailableActions)
        && EqualityComparer<global::Splice.Api.Token.MetadataV1.Metadata>.Default.Equals(Meta, other.Meta);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(OriginalInstructionCid);
        hash.Add(Transfer);
        hash.Add(ExpiresAt);
        hash.Add(DamlFieldCollections.Hash(AvailableActions));
        hash.Add(Meta);
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("originalInstructionCid", OriginalInstructionCid is { } __OriginalInstructionCid ? new DamlOptional(__OriginalInstructionCid.ToDamlValue()) : DamlOptional.None),
        DamlField.Create("transfer", Transfer.ToRecord()),
        DamlField.Create("expiresAt", ExpiresAt is { } __ExpiresAt ? new DamlOptional(new DamlTimestamp(__ExpiresAt)) : DamlOptional.None),
        DamlField.Create("availableActions", new DamlGenMap(AvailableActions.Select(kv => ((DamlValue)kv.Key.ToVariant(), (DamlValue)new DamlList(kv.Value.Select(x => (DamlValue)new DamlList(x.Select(x => (DamlValue)x.ToDamlValue()).ToList())).ToList()))).ToList())),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionView FromRecord(DamlRecord record) => new TransferInstructionView(
        OriginalInstructionCid: record.GetRequiredField("originalInstructionCid").AsOptional().HasValue ? new ContractId<ITransferInstruction>(record.GetRequiredField("originalInstructionCid").AsOptional().Value!.As<DamlContractId>().Value) : null,
        Transfer: Transfer.FromRecord(record.GetRequiredField("transfer").As<DamlRecord>()),
        ExpiresAt: record.GetRequiredField("expiresAt").AsOptional().HasValue ? record.GetRequiredField("expiresAt").AsOptional().Value!.As<DamlTimestamp>().Value : null,
        AvailableActions: (IReadOnlyDictionary<TransferInstructionAction, IReadOnlyList<IReadOnlyList<Party>>>)record.GetRequiredField("availableActions").As<DamlGenMap>().Entries.ToDictionary(kv => TransferInstructionAction.FromVariant(kv.Key.As<DamlVariant>()), kv => (IReadOnlyList<IReadOnlyList<Party>>)kv.Value.As<DamlList>().Values.Select(x => (IReadOnlyList<Party>)x.As<DamlList>().Values.Select(x => Party.FromDamlValue(x.As<DamlParty>())).ToList()).ToList()),
        Meta: global::Splice.Api.Token.MetadataV1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

    /// <summary>Decodes a Daml-LF JSON record directly into a DamlRecord, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlRecord __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context)
    {
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireObject(json, context);
        return DamlRecord.Create(
            DamlField.Create("originalInstructionCid", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadOptional(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "originalInstructionCid"), context.Field("originalInstructionCid"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadContractId(__json0, __ctx0))),
            DamlField.Create("transfer", Transfer.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "transfer"), context.Field("transfer"))),
            DamlField.Create("expiresAt", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadOptional(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "expiresAt"), context.Field("expiresAt"), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadTimestamp(__json0, __ctx0))),
            DamlField.Create("availableActions", global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadGenMap(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "availableActions"), context.Field("availableActions"), (__json0, __ctx0) => TransferInstructionAction.__ReadDamlLfJson(__json0, __ctx0), (__json0, __ctx0) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(__json0, __ctx0, (__json1, __ctx1) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadList(__json1, __ctx1, (__json2, __ctx2) => global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadParty(__json2, __ctx2))))),
            DamlField.Create("meta", global::Splice.Api.Token.MetadataV1.Metadata.__ReadDamlLfJson(global::Daml.Runtime.Serialization.DamlLfJsonDecoders.RequireField(json, context, "meta"), context.Field("meta")))
        );
    }

}
