// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Splice.Api.Token.TransferInstructionV2;

/// <summary>
/// Generated from Daml record TransferInstructionResult
/// </summary>
public sealed record TransferInstructionResult(
    TransferInstructionResult_Output Output,
    IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> SenderChangeCids,
    global::Splice.Api.Token.MetadataV1.Metadata Meta
) : IDamlRecord<TransferInstructionResult>
{
    /// <summary>The Daml field <c>output</c>.</summary>
    [DamlFieldAttribute("output")]
    public TransferInstructionResult_Output Output { get; init; } = Output;

    private readonly IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> _senderChangeCids = DamlFieldCollections.Copy(SenderChangeCids);

    /// <summary>The Daml field <c>senderChangeCids</c>. Copied when this value is constructed and on <c>init</c>, so a later change to the caller's collection cannot alter this value's equality or hash code.</summary>
    [DamlFieldAttribute("senderChangeCids")]
    public IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>> SenderChangeCids
    {
        get => _senderChangeCids;
        init => _senderChangeCids = DamlFieldCollections.Copy(value);
    }

    /// <summary>The Daml field <c>meta</c>.</summary>
    [DamlFieldAttribute("meta")]
    public global::Splice.Api.Token.MetadataV1.Metadata Meta { get; init; } = Meta;

    /// <summary>Compares by content, reading list members element by element and map members key by key independently of insertion order.</summary>
    /// <param name="other">The value to compare against.</param>
    /// <returns><c>true</c> when every member is equal.</returns>
    public bool Equals(TransferInstructionResult? other) =>
        other is not null
        && EqualityComparer<TransferInstructionResult_Output>.Default.Equals(Output, other.Output)
        && DamlFieldCollections.Equal(SenderChangeCids, other.SenderChangeCids)
        && EqualityComparer<global::Splice.Api.Token.MetadataV1.Metadata>.Default.Equals(Meta, other.Meta);

    /// <inheritdoc />
    public override int GetHashCode()
    {
        var hash = new HashCode();
        hash.Add(Output);
        hash.Add(DamlFieldCollections.Hash(SenderChangeCids));
        hash.Add(Meta);
        return hash.ToHashCode();
    }

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("output", Output.ToVariant()),
        DamlField.Create("senderChangeCids", new DamlList(SenderChangeCids.Select(x => (DamlValue)x.ToDamlValue()).ToList())),
        DamlField.Create("meta", Meta.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static TransferInstructionResult FromRecord(DamlRecord record) => new TransferInstructionResult(
        Output: TransferInstructionResult_Output.FromVariant(record.GetRequiredField("output").As<DamlVariant>()),
        SenderChangeCids: (IReadOnlyList<ContractId<global::Splice.Api.Token.HoldingV2.IHolding>>)record.GetRequiredField("senderChangeCids").As<DamlList>().Values.Select(x => new ContractId<global::Splice.Api.Token.HoldingV2.IHolding>(x.As<DamlContractId>().Value)).ToList(),
        Meta: global::Splice.Api.Token.MetadataV1.Metadata.FromRecord(record.GetRequiredField("meta").As<DamlRecord>())
    );

}
