// Copyright (c) 2026 Peaceful Studio OÜ
// SPDX-License-Identifier: Apache-2.0

namespace Daml.Runtime.Contracts;

/// <summary>
/// Helpers for projecting <see cref="TransactionResult.CreatedContracts"/> into typed
/// <see cref="ContractId{T}"/> values by matching template identifier (module + entity).
/// </summary>
/// <remarks>
/// These helpers are template-typed by design — they exist to bridge the
/// (untyped) wire-level <see cref="CreatedContract"/> list back to the C# template
/// classes generated by <c>daml-codegen-csharp</c>. Package id is intentionally not
/// part of the match, so template upgrades that change the package hash but keep the
/// qualified name stable still resolve.
/// </remarks>
public static class TransactionResultExtensions
{
    /// <summary>
    /// Returns the single created <see cref="ContractId{T}"/> matching <typeparamref name="T"/>'s
    /// template identifier. Throws <see cref="InvalidOperationException"/> if zero or
    /// more than one contract of <typeparamref name="T"/> was created.
    /// </summary>
    [System.Diagnostics.CodeAnalysis.SuppressMessage(
        "Naming", "CA1720:Identifier contains type name",
        Justification = "Mirrors Canton/Daml ledger API helper naming.")]
    public static ContractId<T> Single<T>(this TransactionResult result) where T : ITemplate
    {
        ArgumentNullException.ThrowIfNull(result);
        var matches = MatchingContractIds<T>(result);
        return matches.Count switch
        {
            1 => new ContractId<T>(matches[0]),
            0 => throw new InvalidOperationException(
                $"Transaction created no contracts of type {typeof(T).Name}."),
            _ => throw new InvalidOperationException(
                $"Transaction created {matches.Count} contracts of type {typeof(T).Name}, expected exactly 1."),
        };
    }

    /// <summary>
    /// Returns the single created <see cref="ContractId{T}"/> matching <typeparamref name="T"/>'s
    /// template identifier, or <c>null</c> if none was created. Throws
    /// <see cref="InvalidOperationException"/> if more than one was created.
    /// </summary>
    public static ContractId<T>? TrySingle<T>(this TransactionResult result) where T : ITemplate
    {
        ArgumentNullException.ThrowIfNull(result);
        var matches = MatchingContractIds<T>(result);
        return matches.Count switch
        {
            0 => null,
            1 => new ContractId<T>(matches[0]),
            _ => throw new InvalidOperationException(
                $"Transaction created {matches.Count} contracts of type {typeof(T).Name}, expected at most 1."),
        };
    }

    /// <summary>
    /// Returns all created <see cref="ContractId{T}"/> matching <typeparamref name="T"/>'s
    /// template identifier, in transaction order.
    /// </summary>
    public static IReadOnlyList<ContractId<T>> All<T>(this TransactionResult result) where T : ITemplate
    {
        ArgumentNullException.ThrowIfNull(result);
        var matches = MatchingContractIds<T>(result);
        var ids = new ContractId<T>[matches.Count];
        for (var i = 0; i < matches.Count; i++)
        {
            ids[i] = new ContractId<T>(matches[i]);
        }
        return ids;
    }

    private static List<string> MatchingContractIds<T>(TransactionResult result) where T : ITemplate
    {
        var expected = T.TemplateId;
        var matches = new List<string>(result.CreatedContracts.Count);
        foreach (var created in result.CreatedContracts)
        {
            if (string.Equals(created.TemplateId.ModuleName, expected.ModuleName, StringComparison.Ordinal)
                && string.Equals(created.TemplateId.EntityName, expected.EntityName, StringComparison.Ordinal))
            {
                matches.Add(created.ContractId);
            }
        }
        return matches;
    }
}
