// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml enum AmuletConversionRateFeed_ArchiveAsDsoResult
/// </summary>
public enum AmuletConversionRateFeed_ArchiveAsDsoResult
{
    AmuletConversionRateFeed_ArchiveAsDsoResult,
}

/// <summary>
/// Extension methods for AmuletConversionRateFeed_ArchiveAsDsoResult serialization.
/// </summary>
public static class AmuletConversionRateFeed_ArchiveAsDsoResultExtensions
{
    /// <summary>Converts to a DamlEnum value.</summary>
    public static DamlEnum ToDamlEnum(this AmuletConversionRateFeed_ArchiveAsDsoResult value)
    {
        return value switch
        {
            AmuletConversionRateFeed_ArchiveAsDsoResult.AmuletConversionRateFeed_ArchiveAsDsoResult => DamlEnum.Create("AmuletConversionRateFeed_ArchiveAsDsoResult"),
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
        };
    }

    /// <summary>Creates an instance from a DamlEnum value.</summary>
    public static AmuletConversionRateFeed_ArchiveAsDsoResult FromDamlEnum(DamlEnum value)
    {
        return value.Constructor switch
        {
            "AmuletConversionRateFeed_ArchiveAsDsoResult" => AmuletConversionRateFeed_ArchiveAsDsoResult.AmuletConversionRateFeed_ArchiveAsDsoResult,
            _ => throw new ArgumentOutOfRangeException(nameof(value), value.Constructor, null)
        };
    }
}
