// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Amulet.Name.Service;

public sealed partial record AmuletConversionRateFeed
{
    /// <summary>
    /// Choice argument type for AmuletConversionRateFeed_ArchiveAsDso.
    /// </summary>
    public sealed record AmuletConversionRateFeed_ArchiveAsDso([property: DamlFieldAttribute("reason")] string Reason) : IDamlRecord
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("reason", new DamlText(Reason))
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AmuletConversionRateFeed_ArchiveAsDso FromRecord(DamlRecord record) => new AmuletConversionRateFeed_ArchiveAsDso(
            Reason: record.GetRequiredField("reason").As<DamlText>().Value
        );

    }
}
