// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Ledger.Abstractions.Extensions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml template Splice.Ans.AmuletConversionRateFeed:AmuletConversionRateFeed
/// </summary>
public sealed partial record AmuletConversionRateFeed(
    [property: DamlFieldAttribute("publisher")] Party Publisher,
    [property: DamlFieldAttribute("dso")] Party Dso,
    [property: DamlFieldAttribute("nextUpdateAfter")] DateTimeOffset? NextUpdateAfter,
    [property: DamlFieldAttribute("amuletConversionRate")] decimal AmuletConversionRate
) : ITemplate, IDamlRecord<AmuletConversionRateFeed>
{
    /// <summary>Gets the template identifier.</summary>
    public static Identifier TemplateId { get; } = new("9cffe65feb664c9550937433067e9f969e3795c6fb38715e06a5e04fc1ae1f83", "Splice.Ans.AmuletConversionRateFeed", "AmuletConversionRateFeed");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "9cffe65feb664c9550937433067e9f969e3795c6fb38715e06a5e04fc1ae1f83";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static Version PackageVersion { get; } = new(0, 1, 23);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("publisher", Publisher.ToDamlValue()),
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("nextUpdateAfter", NextUpdateAfter is { } __NextUpdateAfter ? new DamlOptional(new DamlTimestamp(__NextUpdateAfter)) : DamlOptional.None),
        DamlField.Create("amuletConversionRate", new DamlNumeric(AmuletConversionRate))
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AmuletConversionRateFeed FromRecord(DamlRecord record) => new AmuletConversionRateFeed(
        Publisher: Party.FromDamlValue(record.GetRequiredField("publisher").As<DamlParty>()),
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        NextUpdateAfter: record.GetRequiredField("nextUpdateAfter").AsOptional().HasValue ? record.GetRequiredField("nextUpdateAfter").AsOptional().Value!.As<DamlTimestamp>().Value : null,
        AmuletConversionRate: record.GetRequiredField("amuletConversionRate").As<DamlNumeric>().Value
    );

    /// <summary>
    /// Exercise the AmuletConversionRateFeed_ArchiveAsDso choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AmuletConversionRateFeed, AmuletConversionRateFeed_ArchiveAsDso, AmuletConversionRateFeed_ArchiveAsDsoResult> ChoiceAmuletConversionRateFeed_ArchiveAsDso { get; } = new()
    {
        Name = new ChoiceName("AmuletConversionRateFeed_ArchiveAsDso"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AmuletConversionRateFeed_ArchiveAsDsoResultExtensions.FromDamlEnum(val.As<DamlEnum>())
    };

    /// <summary>
    /// Exercise the AmuletConversionRateFeed_Update choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AmuletConversionRateFeed, AmuletConversionRateFeed_Update, AmuletConversionRateFeed_UpdateResult> ChoiceAmuletConversionRateFeed_Update { get; } = new()
    {
        Name = new ChoiceName("AmuletConversionRateFeed_Update"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AmuletConversionRateFeed_UpdateResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AmuletConversionRateFeed, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlRecord.Create(),
        ResultDecoder = _ => DamlUnit.Instance
    };

    /// <summary>Contract ID for AmuletConversionRateFeed.</summary>
    [global::System.Text.Json.Serialization.JsonConverter(typeof(global::Daml.Runtime.Serialization.ContractIdJsonConverterFactory))]
    public sealed record ContractId(string Value) : ContractId<AmuletConversionRateFeed>(Value), IExercises<AmuletConversionRateFeed>
    {
        ContractId<AmuletConversionRateFeed> IExercises<AmuletConversionRateFeed>.ContractId => this;
    }

    /// <summary>Active contract for AmuletConversionRateFeed.</summary>
    public sealed record Contract(ContractId Id, AmuletConversionRateFeed Data) : IContract<ContractId, AmuletConversionRateFeed>
    {
        /// <summary>Creates a Contract from a CreatedEvent.</summary>
        public static Contract FromCreatedEvent(CreatedEvent @event) =>
            new(new ContractId(@event.ContractId), global::Splice.Amulet.Name.Service.AmuletConversionRateFeed.FromRecord(@event.CreateArguments));
    }
}


/// <summary>
/// Typed-submitter extensions for <see cref="AmuletConversionRateFeed"/>. The
/// <see cref="CreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AmuletConversionRateFeedSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AmuletConversionRateFeed"/> contract on the ledger.
    /// The submitting parties are derived from the payload — each Daml signatory is
    /// a reference to a payload field, so the caller never restates a party that's
    /// already in the record.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<ContractId<AmuletConversionRateFeed>>> CreateAsync(
        this ILedgerWriter client,
        AmuletConversionRateFeed payload,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(payload);

        SubmitterInfo submitter = payload.Publisher;

        return client.TryCreateAsync<AmuletConversionRateFeed>(payload, submitter, cancellationToken: cancellationToken);
    }

    /// <summary>
    /// Returns the observers of a <see cref="AmuletConversionRateFeed"/> payload —
    /// the parties named in the Daml <c>observer</c> clause, derived from
    /// the payload's <c>Party</c> properties in declaration order. Useful
    /// for inspecting / asserting the observer set without exercising a
    /// choice.
    /// </summary>
    /// <param name="payload">The contract payload.</param>
    public static IReadOnlyList<Party> Observers(AmuletConversionRateFeed payload)
    {
        ArgumentNullException.ThrowIfNull(payload);
        return new Party[]
        {
            payload.Dso
        };
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="AmuletConversionRateFeed"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>SingleCommandExtensions.TrySubmitSingleAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AmuletConversionRateFeedNonContractExtensions
{
    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AmuletConversionRateFeed_ArchiveAsDso choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AmuletConversionRateFeed_ArchiveAsDsoCommand(
        this ContractId<AmuletConversionRateFeed> contractId,
        AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDso argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AmuletConversionRateFeed.TemplateId,
            contractId,
            new ChoiceName("AmuletConversionRateFeed_ArchiveAsDso"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AmuletConversionRateFeed_ArchiveAsDso choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AmuletConversionRateFeed_ArchiveAsDsoResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AmuletConversionRateFeed_ArchiveAsDsoResult>> AmuletConversionRateFeed_ArchiveAsDsoAsync(
        this ContractId<AmuletConversionRateFeed> contractId,
        ILedgerWriter client,
        AmuletConversionRateFeed.AmuletConversionRateFeed_ArchiveAsDso argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AmuletConversionRateFeed_ArchiveAsDsoCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAmuletConversionRateFeed_ArchiveAsDsoResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the AmuletConversionRateFeed_Update choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="argument">The choice argument.</param>
    public static ExerciseCommand AmuletConversionRateFeed_UpdateCommand(
        this ContractId<AmuletConversionRateFeed> contractId,
        AmuletConversionRateFeed.AmuletConversionRateFeed_Update argument)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(argument);
        return new ExerciseCommand(
            AmuletConversionRateFeed.TemplateId,
            contractId,
            new ChoiceName("AmuletConversionRateFeed_Update"),
            argument.ToRecord());
    }

    /// <summary>
    /// Exercises the AmuletConversionRateFeed_Update choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AmuletConversionRateFeed_UpdateResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AmuletConversionRateFeed_UpdateResult>> AmuletConversionRateFeed_UpdateAsync(
        this ContractId<AmuletConversionRateFeed> contractId,
        ILedgerWriter client,
        AmuletConversionRateFeed.AmuletConversionRateFeed_Update argument,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.AmuletConversionRateFeed_UpdateCommand(argument);

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectAmuletConversionRateFeed_UpdateResult(tx, contractId.Value));
    }

    /// <summary>
    /// Builds the <see cref="global::Daml.Runtime.Commands.ExerciseCommand"/> for the Archive choice on this contract id.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    public static ExerciseCommand ArchiveCommand(
        this ContractId<AmuletConversionRateFeed> contractId)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        return new ExerciseCommand(
            AmuletConversionRateFeed.TemplateId,
            contractId,
            new ChoiceName("Archive"),
            DamlRecord.Create());
    }

    /// <summary>
    /// Exercises the Archive choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>Unit</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>), so a submitter that must read contracts it does not act as stays expressible.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="commandId">Optional command id for deduplication; a fresh id is minted only when omitted, and a minted id is not reported back on a failed submission. Supply and retain your own id to make a retry of a lost-but-accepted submission deduplicable, so the ledger deduplicates the resubmission instead of re-executing the choice.</param>
    /// <param name="timeout">Optional per-call deadline, applied best-effort by the transport; transports without a server-side deadline apply a client-side bound only. The default <c>null</c> applies no deadline. An overrun surfaces as an <c>InfraError</c> outcome.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<Unit>> ArchiveAsync(
        this ContractId<AmuletConversionRateFeed> contractId,
        ILedgerWriter client,
        SubmitterInfo submitter,
        string? workflowId = null,
        CommandId? commandId = null,
        TimeSpan? timeout = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);

        var command = contractId.ArchiveCommand();

        var outcome = await client.TrySubmitSingleAsync(command, submitter, workflowId, commandId, timeout, cancellationToken).ConfigureAwait(false);

        return outcome.ProjectCommitted(tx => ProjectArchiveResult(tx, contractId.Value));
    }

    private static ExerciseOutcome<AmuletConversionRateFeed_ArchiveAsDsoResult> ProjectAmuletConversionRateFeed_ArchiveAsDsoResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AmuletConversionRateFeed.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AmuletConversionRateFeed.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AmuletConversionRateFeed_ArchiveAsDso", StringComparison.Ordinal))
            {
                var decoded = AmuletConversionRateFeed.ChoiceAmuletConversionRateFeed_ArchiveAsDso.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AmuletConversionRateFeed_ArchiveAsDsoResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AmuletConversionRateFeed_ArchiveAsDso' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AmuletConversionRateFeed_UpdateResult> ProjectAmuletConversionRateFeed_UpdateResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AmuletConversionRateFeed.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AmuletConversionRateFeed.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AmuletConversionRateFeed_Update", StringComparison.Ordinal))
            {
                var decoded = AmuletConversionRateFeed.ChoiceAmuletConversionRateFeed_Update.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AmuletConversionRateFeed_UpdateResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AmuletConversionRateFeed_Update' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<Unit> ProjectArchiveResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AmuletConversionRateFeed.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AmuletConversionRateFeed.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "Archive", StringComparison.Ordinal))
            {
                return new ExerciseOutcome<Unit>.One(Unit.Value);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'Archive' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerWriter implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerWriter implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
