// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using System;

namespace Splice.Amulet.Name.Service;

public sealed partial record AmuletConversionRateFeed
{
    /// <summary>
    /// Choice argument type for AmuletConversionRateFeed_Update.
    /// </summary>
    public sealed record AmuletConversionRateFeed_Update([property: DamlFieldAttribute("amuletConversionRate")] decimal AmuletConversionRate, [property: DamlFieldAttribute("amuletRulesCid")] ContractId<Splice.Amulet.AmuletRules> AmuletRulesCid, [property: DamlFieldAttribute("markerContextO")] MarkerContext? MarkerContextO, [property: DamlFieldAttribute("newNextUpdateAfter")] DateTimeOffset NewNextUpdateAfter) : IDamlRecord
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("amuletConversionRate", new DamlNumeric(AmuletConversionRate)),
            DamlField.Create("amuletRulesCid", AmuletRulesCid.ToDamlValue()),
            DamlField.Create("markerContextO", MarkerContextO is { } __MarkerContextO ? new DamlOptional(__MarkerContextO.ToRecord()) : DamlOptional.None),
            DamlField.Create("newNextUpdateAfter", new DamlTimestamp(NewNextUpdateAfter))
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AmuletConversionRateFeed_Update FromRecord(DamlRecord record) => new AmuletConversionRateFeed_Update(
            AmuletConversionRate: record.GetRequiredField("amuletConversionRate").As<DamlNumeric>().Value,
            AmuletRulesCid: new ContractId<Splice.Amulet.AmuletRules>(record.GetRequiredField("amuletRulesCid").As<DamlContractId>().Value),
            MarkerContextO: record.GetRequiredField("markerContextO").AsOptional().HasValue ? MarkerContext.FromRecord(record.GetRequiredField("markerContextO").AsOptional().Value!.As<DamlRecord>()) : null,
            NewNextUpdateAfter: record.GetRequiredField("newNextUpdateAfter").As<DamlTimestamp>().Value
        );

    }
}
