// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml record AnsEntryContext_RejectEntryInitialPaymentResult
/// </summary>
public sealed record AnsEntryContext_RejectEntryInitialPaymentResult([property: DamlFieldAttribute("amuletSum")] Splice.Amulet.AmuletCreateSummary<ContractId<Splice.Amulet.Amulet>> AmuletSum) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("amuletSum", AmuletSum.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntryContext_RejectEntryInitialPaymentResult FromRecord(DamlRecord record) => new AnsEntryContext_RejectEntryInitialPaymentResult(
        AmuletSum: default(Splice.Amulet.AmuletCreateSummary<ContractId<Splice.Amulet.Amulet>>)! /* TODO: Implement deserialization for DamlTypeApp { IsOptional = False, Base = DamlTypeRef { IsOptional = False, PackageId = 23f47481dab6b1ec01339d6e14494d85bb2844c25f45b26fc5c9ef4cd4942d1f, Module = Splice.Amulet, Name = AmuletCreateSummary }, Arguments = System.Collections.Generic.List`1[Daml.Codegen.CSharp.Model.DamlType] } */
    );

}
