// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml template Splice.Ans:AnsEntryContext
/// </summary>
public sealed partial record AnsEntryContext([property: DamlFieldAttribute("dso")] Party Dso, [property: DamlFieldAttribute("user")] Party User, [property: DamlFieldAttribute("name")] string Name, [property: DamlFieldAttribute("url")] string Url, [property: DamlFieldAttribute("description")] string Description, [property: DamlFieldAttribute("reference")] ContractId<Splice.Wallet.Payments.SubscriptionRequest> Reference) : ITemplate
{
    /// <summary>Gets the template identifier.</summary>
    public static Identifier TemplateId { get; } = new("b342bbbd425902283c20eb5011eeab90cc9f69b4c534b8b757fd51b8ca7be589", "Splice.Ans", "AnsEntryContext");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "b342bbbd425902283c20eb5011eeab90cc9f69b4c534b8b757fd51b8ca7be589";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static Version PackageVersion { get; } = new(0, 1, 21);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("user", User.ToDamlValue()),
        DamlField.Create("name", new DamlText(Name)),
        DamlField.Create("url", new DamlText(Url)),
        DamlField.Create("description", new DamlText(Description)),
        DamlField.Create("reference", Reference.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntryContext FromRecord(DamlRecord record) => new AnsEntryContext(
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        User: Party.FromDamlValue(record.GetRequiredField("user").As<DamlParty>()),
        Name: record.GetRequiredField("name").As<DamlText>().Value,
        Url: record.GetRequiredField("url").As<DamlText>().Value,
        Description: record.GetRequiredField("description").As<DamlText>().Value,
        Reference: new ContractId<Splice.Wallet.Payments.SubscriptionRequest>(record.GetRequiredField("reference").As<DamlContractId>().Value)
    );

    /// <summary>
    /// Exercise the AnsEntryContext_CollectEntryRenewalPayment choice.
    /// </summary>
    public static Choice<AnsEntryContext, AnsEntryContext_CollectEntryRenewalPayment, AnsEntryContext_CollectEntryRenewalPaymentResult> ChoiceAnsEntryContext_CollectEntryRenewalPayment { get; } = new()
    {
        Name = new ChoiceName("AnsEntryContext_CollectEntryRenewalPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsEntryContext_CollectEntryRenewalPaymentResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the AnsEntryContext_CollectInitialEntryPayment choice.
    /// </summary>
    public static Choice<AnsEntryContext, AnsEntryContext_CollectInitialEntryPayment, AnsEntryContext_CollectInitialEntryPaymentResult> ChoiceAnsEntryContext_CollectInitialEntryPayment { get; } = new()
    {
        Name = new ChoiceName("AnsEntryContext_CollectInitialEntryPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsEntryContext_CollectInitialEntryPaymentResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the AnsEntryContext_RejectEntryInitialPayment choice.
    /// </summary>
    public static Choice<AnsEntryContext, AnsEntryContext_RejectEntryInitialPayment, AnsEntryContext_RejectEntryInitialPaymentResult> ChoiceAnsEntryContext_RejectEntryInitialPayment { get; } = new()
    {
        Name = new ChoiceName("AnsEntryContext_RejectEntryInitialPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsEntryContext_RejectEntryInitialPaymentResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the AnsEntryContext_Terminate choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsEntryContext, AnsEntryContext_Terminate, AnsEntryContext_TerminateResult> ChoiceAnsEntryContext_Terminate { get; } = new()
    {
        Name = new ChoiceName("AnsEntryContext_Terminate"),
        Consuming = true,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsEntryContext_TerminateResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsEntryContext, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlUnit.Instance,
        ResultDecoder = _ => DamlUnit.Instance
    };

    /// <summary>Contract ID for AnsEntryContext.</summary>
    public sealed record ContractId(string Value) : ContractId<AnsEntryContext>(Value), IExercises<AnsEntryContext>
    {
        ContractId<AnsEntryContext> IExercises<AnsEntryContext>.ContractId => this;
    }

    /// <summary>Active contract for AnsEntryContext.</summary>
    public sealed record Contract(ContractId Id, AnsEntryContext Data) : IContract<ContractId, AnsEntryContext>
    {
        /// <summary>Creates a Contract from a CreatedEvent.</summary>
        public static Contract FromCreatedEvent(CreatedEvent @event) =>
            new(new ContractId(@event.ContractId), AnsEntryContext.FromRecord(@event.CreateArguments));
    }
}


/// <summary>
/// Typed-submitter extensions for <see cref="AnsEntryContext"/>. The
/// <see cref="CreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AnsEntryContextSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AnsEntryContext"/> contract on the ledger.
    /// The submitter is passed explicitly via <paramref name="submitter"/>. The static
    /// analyzer could not resolve the Daml <c>signatory</c> clause to payload-field
    /// references — typically because the expression involves the template key, a
    /// constant, or a function call. <see cref="SubmitterInfo"/> implicitly converts
    /// from a single <c>Party</c>, so single-party callers still pass one literal.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<ContractId<AnsEntryContext>>> CreateAsync(
        this ILedgerClient client,
        AnsEntryContext payload,
        SubmitterInfo submitter,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(payload);

        return client.TryCreateAsync<AnsEntryContext>(payload, submitter, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="AnsEntryContext"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>ILedgerClient.TrySubmitAndWaitForTransactionAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AnsEntryContextNonContractExtensions
{
    /// <summary>
    /// Exercises the AnsEntryContext_CollectEntryRenewalPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsEntryContext_CollectEntryRenewalPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsEntryContext_CollectEntryRenewalPaymentResult>> AnsEntryContext_CollectEntryRenewalPaymentAsync(
        this ContractId<AnsEntryContext> contractId,
        ILedgerClient client,
        AnsEntryContext.AnsEntryContext_CollectEntryRenewalPayment argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsEntryContext.TemplateId,
            contractId,
            new ChoiceName("AnsEntryContext_CollectEntryRenewalPayment"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsEntryContext_CollectEntryRenewalPaymentResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsEntryContext_CollectEntryRenewalPaymentResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsEntryContext_CollectEntryRenewalPaymentResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    /// <summary>
    /// Exercises the AnsEntryContext_CollectInitialEntryPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsEntryContext_CollectInitialEntryPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsEntryContext_CollectInitialEntryPaymentResult>> AnsEntryContext_CollectInitialEntryPaymentAsync(
        this ContractId<AnsEntryContext> contractId,
        ILedgerClient client,
        AnsEntryContext.AnsEntryContext_CollectInitialEntryPayment argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsEntryContext.TemplateId,
            contractId,
            new ChoiceName("AnsEntryContext_CollectInitialEntryPayment"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsEntryContext_CollectInitialEntryPaymentResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsEntryContext_CollectInitialEntryPaymentResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsEntryContext_CollectInitialEntryPaymentResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    /// <summary>
    /// Exercises the AnsEntryContext_RejectEntryInitialPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsEntryContext_RejectEntryInitialPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsEntryContext_RejectEntryInitialPaymentResult>> AnsEntryContext_RejectEntryInitialPaymentAsync(
        this ContractId<AnsEntryContext> contractId,
        ILedgerClient client,
        AnsEntryContext.AnsEntryContext_RejectEntryInitialPayment argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsEntryContext.TemplateId,
            contractId,
            new ChoiceName("AnsEntryContext_RejectEntryInitialPayment"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsEntryContext_RejectEntryInitialPaymentResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsEntryContext_RejectEntryInitialPaymentResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsEntryContext_RejectEntryInitialPaymentResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    /// <summary>
    /// Exercises the AnsEntryContext_Terminate choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsEntryContext_TerminateResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsEntryContext_TerminateResult>> AnsEntryContext_TerminateAsync(
        this ContractId<AnsEntryContext> contractId,
        ILedgerClient client,
        AnsEntryContext.AnsEntryContext_Terminate argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsEntryContext.TemplateId,
            contractId,
            new ChoiceName("AnsEntryContext_Terminate"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsEntryContext_TerminateResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsEntryContext_TerminateResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsEntryContext_TerminateResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    private static ExerciseOutcome<AnsEntryContext_CollectEntryRenewalPaymentResult> ProjectAnsEntryContext_CollectEntryRenewalPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntryContext.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntryContext.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsEntryContext_CollectEntryRenewalPayment", StringComparison.Ordinal))
            {
                var decoded = AnsEntryContext.ChoiceAnsEntryContext_CollectEntryRenewalPayment.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsEntryContext_CollectEntryRenewalPaymentResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsEntryContext_CollectEntryRenewalPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsEntryContext_CollectInitialEntryPaymentResult> ProjectAnsEntryContext_CollectInitialEntryPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntryContext.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntryContext.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsEntryContext_CollectInitialEntryPayment", StringComparison.Ordinal))
            {
                var decoded = AnsEntryContext.ChoiceAnsEntryContext_CollectInitialEntryPayment.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsEntryContext_CollectInitialEntryPaymentResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsEntryContext_CollectInitialEntryPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsEntryContext_RejectEntryInitialPaymentResult> ProjectAnsEntryContext_RejectEntryInitialPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntryContext.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntryContext.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsEntryContext_RejectEntryInitialPayment", StringComparison.Ordinal))
            {
                var decoded = AnsEntryContext.ChoiceAnsEntryContext_RejectEntryInitialPayment.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsEntryContext_RejectEntryInitialPaymentResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsEntryContext_RejectEntryInitialPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsEntryContext_TerminateResult> ProjectAnsEntryContext_TerminateResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsEntryContext.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsEntryContext.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsEntryContext_Terminate", StringComparison.Ordinal))
            {
                var decoded = AnsEntryContext.ChoiceAnsEntryContext_Terminate.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsEntryContext_TerminateResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsEntryContext_Terminate' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
