// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Amulet.Name.Service;

public sealed partial record AnsEntry
{
    /// <summary>
    /// Choice argument type for AnsEntry_Expire.
    /// </summary>
    public sealed record AnsEntry_Expire([property: DamlFieldAttribute("actor")] Party Actor) : IDamlRecord
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("actor", Actor.ToDamlValue())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AnsEntry_Expire FromRecord(DamlRecord record) => new AnsEntry_Expire(
            Actor: Party.FromDamlValue(record.GetRequiredField("actor").As<DamlParty>())
        );

    }
}
