// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml record AnsEntry_ExpireResult
/// </summary>
public sealed record AnsEntry_ExpireResult : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create();

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsEntry_ExpireResult FromRecord(DamlRecord record) => new AnsEntry_ExpireResult();

}
