// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Ledger.Abstractions;
using Daml.Runtime.Commands;
using Daml.Runtime.Contracts;
using Daml.Runtime.Data;
using Daml.Runtime.Outcomes;
using Daml.Runtime.Stdlib;
using System;
using System.Threading;
using System.Threading.Tasks;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml template Splice.Ans:AnsRules
/// </summary>
public sealed partial record AnsRules([property: DamlFieldAttribute("dso")] Party Dso, [property: DamlFieldAttribute("config")] AnsRulesConfig Config) : ITemplate
{
    /// <summary>Gets the template identifier.</summary>
    public static Identifier TemplateId { get; } = new("b342bbbd425902283c20eb5011eeab90cc9f69b4c534b8b757fd51b8ca7be589", "Splice.Ans", "AnsRules");

    /// <summary>Gets the package ID.</summary>
    public static string PackageId => "b342bbbd425902283c20eb5011eeab90cc9f69b4c534b8b757fd51b8ca7be589";

    /// <summary>Gets the package name.</summary>
    public static string PackageName => "splice-amulet-name-service";

    /// <summary>Gets the package version.</summary>
    public static Version PackageVersion { get; } = new(0, 1, 21);

    /// <summary>Gets the compile-time Daml type descriptor.</summary>
    public static DamlTypeDescriptor DamlTypeId { get; } = new(TemplateId, DamlTypeKind.Template, PackageName);

    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("config", Config.ToRecord())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static AnsRules FromRecord(DamlRecord record) => new AnsRules(
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        Config: AnsRulesConfig.FromRecord(record.GetRequiredField("config").As<DamlRecord>())
    );

    /// <summary>
    /// Exercise the AnsRules_CollectEntryRenewalPayment choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_CollectEntryRenewalPayment, AnsRules_CollectEntryRenewalPaymentResult> ChoiceAnsRules_CollectEntryRenewalPayment { get; } = new()
    {
        Name = new ChoiceName("AnsRules_CollectEntryRenewalPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsRules_CollectEntryRenewalPaymentResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the AnsRules_CollectInitialEntryPayment choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_CollectInitialEntryPayment, AnsRules_CollectInitialEntryPaymentResult> ChoiceAnsRules_CollectInitialEntryPayment { get; } = new()
    {
        Name = new ChoiceName("AnsRules_CollectInitialEntryPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsRules_CollectInitialEntryPaymentResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the AnsRules_RejectEntryInitialPayment choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_RejectEntryInitialPayment, AnsRules_RejectEntryInitialPaymentResult> ChoiceAnsRules_RejectEntryInitialPayment { get; } = new()
    {
        Name = new ChoiceName("AnsRules_RejectEntryInitialPayment"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsRules_RejectEntryInitialPaymentResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the AnsRules_RequestEntry choice.
    /// </summary>
    public static Choice<AnsRules, AnsRules_RequestEntry, AnsRules_RequestEntryResult> ChoiceAnsRules_RequestEntry { get; } = new()
    {
        Name = new ChoiceName("AnsRules_RequestEntry"),
        Consuming = false,
        ArgumentEncoder = arg => arg.ToRecord(),
        ResultDecoder = val => AnsRules_RequestEntryResult.FromRecord(val.As<DamlRecord>())
    };

    /// <summary>
    /// Exercise the Archive choice.
    /// This choice is consuming and will archive the contract.
    /// </summary>
    public static Choice<AnsRules, DamlUnit, DamlUnit> ChoiceArchive { get; } = new()
    {
        Name = new ChoiceName("Archive"),
        Consuming = true,
        ArgumentEncoder = _ => DamlUnit.Instance,
        ResultDecoder = _ => DamlUnit.Instance
    };

    /// <summary>Contract ID for AnsRules.</summary>
    public sealed record ContractId(string Value) : ContractId<AnsRules>(Value), IExercises<AnsRules>
    {
        ContractId<AnsRules> IExercises<AnsRules>.ContractId => this;
    }

    /// <summary>Active contract for AnsRules.</summary>
    public sealed record Contract(ContractId Id, AnsRules Data) : IContract<ContractId, AnsRules>
    {
        /// <summary>Creates a Contract from a CreatedEvent.</summary>
        public static Contract FromCreatedEvent(CreatedEvent @event) =>
            new(new ContractId(@event.ContractId), AnsRules.FromRecord(@event.CreateArguments));
    }
}


/// <summary>
/// Typed-submitter extensions for <see cref="AnsRules"/>. The
/// <see cref="CreateAsync"/> overload derives the <c>actAs</c> parties
/// from the template payload (for signatories that are payload-field
/// references) and from the caller's explicit arguments (for signatories
/// the static analyzer could not resolve). When the template's
/// <c>observer</c> clause is statically resolvable, an
/// <c>Observers(payload)</c> documentation helper is also emitted.
/// </summary>
public static class AnsRulesSubmissionExtensions
{
    /// <summary>
    /// Creates a new <see cref="AnsRules"/> contract on the ledger.
    /// The submitter is passed explicitly via <paramref name="submitter"/>. The static
    /// analyzer could not resolve the Daml <c>signatory</c> clause to payload-field
    /// references — typically because the expression involves the template key, a
    /// constant, or a function call. <see cref="SubmitterInfo"/> implicitly converts
    /// from a single <c>Party</c>, so single-party callers still pass one literal.
    /// </summary>
    /// <param name="client">The ledger client.</param>
    /// <param name="payload">The contract payload.</param>
    /// <param name="submitter">The submitter party set (<c>actAs</c> + optional <c>readAs</c>).</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static Task<ExerciseOutcome<ContractId<AnsRules>>> CreateAsync(
        this ILedgerClient client,
        AnsRules payload,
        SubmitterInfo submitter,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(client);
        ArgumentNullException.ThrowIfNull(payload);

        return client.TryCreateAsync<AnsRules>(payload, submitter, cancellationToken: cancellationToken);
    }
}

/// <summary>
/// Async exerciser extensions for <see cref="AnsRules"/> contract IDs whose choices
/// return a non-contract-id payload (Decimal, records, lists, Unit, etc.).
/// Each method submits the choice via
/// <c>ILedgerClient.TrySubmitAndWaitForTransactionAsync</c> and lifts the typed result
/// into <c>ExerciseOutcome&lt;TReturn&gt;</c>.
/// </summary>
public static class AnsRulesNonContractExtensions
{
    /// <summary>
    /// Exercises the AnsRules_CollectEntryRenewalPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_CollectEntryRenewalPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>> AnsRules_CollectEntryRenewalPaymentAsync(
        this ContractId<AnsRules> contractId,
        ILedgerClient client,
        AnsRules.AnsRules_CollectEntryRenewalPayment argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_CollectEntryRenewalPayment"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsRules_CollectEntryRenewalPaymentResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    /// <summary>
    /// Exercises the AnsRules_CollectInitialEntryPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_CollectInitialEntryPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>> AnsRules_CollectInitialEntryPaymentAsync(
        this ContractId<AnsRules> contractId,
        ILedgerClient client,
        AnsRules.AnsRules_CollectInitialEntryPayment argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_CollectInitialEntryPayment"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsRules_CollectInitialEntryPaymentResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    /// <summary>
    /// Exercises the AnsRules_RejectEntryInitialPayment choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_RejectEntryInitialPaymentResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>> AnsRules_RejectEntryInitialPaymentAsync(
        this ContractId<AnsRules> contractId,
        ILedgerClient client,
        AnsRules.AnsRules_RejectEntryInitialPayment argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_RejectEntryInitialPayment"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsRules_RejectEntryInitialPaymentResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    /// <summary>
    /// Exercises the AnsRules_RequestEntry choice and lifts the choice's exercise result to
    /// <see cref="ExerciseOutcome{T}"/> over <c>AnsRules_RequestEntryResult</c>. Structured Canton/Daml errors
    /// and infrastructure/transport errors pass through unchanged.
    /// </summary>
    /// <param name="contractId">The contract on which to exercise the choice.</param>
    /// <param name="client">The ledger client.</param>
    /// <param name="argument">The choice argument.</param>
    /// <param name="actAs">The party submitting the command.</param>
    /// <param name="workflowId">Optional workflow id; passed through to the ledger when supplied. No default — workflow IDs are correlation keys, and a per-choice default would bucket every submission of the same choice under one ID.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    public static async Task<ExerciseOutcome<AnsRules_RequestEntryResult>> AnsRules_RequestEntryAsync(
        this ContractId<AnsRules> contractId,
        ILedgerClient client,
        AnsRules.AnsRules_RequestEntry argument,
        Party actAs,
        string? workflowId = null,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(contractId);
        ArgumentNullException.ThrowIfNull(client);

        var command = new ExerciseCommand(
            AnsRules.TemplateId,
            contractId,
            new ChoiceName("AnsRules_RequestEntry"),
            argument.ToRecord());

        var submission = CommandsSubmission.Single(command)
            .WithActAs(actAs)
            .WithCommandId(new CommandId(Guid.NewGuid().ToString()));
        if (!string.IsNullOrEmpty(workflowId))
        {
            submission = submission.WithWorkflowId(new WorkflowId(workflowId));
        }

        var outcome = await client.TrySubmitAndWaitForTransactionAsync(submission, cancellationToken).ConfigureAwait(false);

        return outcome switch
        {
            ExerciseOutcome<TransactionResult>.One success => ProjectAnsRules_RequestEntryResult(success.Result, contractId.Value),
            ExerciseOutcome<TransactionResult>.DamlError damlError => new ExerciseOutcome<AnsRules_RequestEntryResult>.DamlError(damlError.Category, damlError.ErrorId, damlError.Message, damlError.Metadata),
            ExerciseOutcome<TransactionResult>.InfraError infraError => new ExerciseOutcome<AnsRules_RequestEntryResult>.InfraError(infraError.StatusCode, infraError.Message),
            _ => throw new InvalidOperationException($"Unhandled outcome: {outcome.GetType().Name}"),
        };
    }

    private static ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult> ProjectAnsRules_CollectEntryRenewalPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_CollectEntryRenewalPayment", StringComparison.Ordinal))
            {
                var decoded = AnsRules.ChoiceAnsRules_CollectEntryRenewalPayment.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsRules_CollectEntryRenewalPaymentResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_CollectEntryRenewalPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult> ProjectAnsRules_CollectInitialEntryPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_CollectInitialEntryPayment", StringComparison.Ordinal))
            {
                var decoded = AnsRules.ChoiceAnsRules_CollectInitialEntryPayment.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsRules_CollectInitialEntryPaymentResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_CollectInitialEntryPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult> ProjectAnsRules_RejectEntryInitialPaymentResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_RejectEntryInitialPayment", StringComparison.Ordinal))
            {
                var decoded = AnsRules.ChoiceAnsRules_RejectEntryInitialPayment.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsRules_RejectEntryInitialPaymentResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_RejectEntryInitialPayment' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }

    private static ExerciseOutcome<AnsRules_RequestEntryResult> ProjectAnsRules_RequestEntryResult(TransactionResult tx, string contractId)
    {
        foreach (var exercised in tx.ExercisedEvents)
        {
            if (string.Equals(exercised.ContractId, contractId, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.ModuleName, AnsRules.TemplateId.ModuleName, StringComparison.Ordinal)
                && string.Equals(exercised.TemplateId.EntityName, AnsRules.TemplateId.EntityName, StringComparison.Ordinal)
                && string.Equals(exercised.ChoiceName, "AnsRules_RequestEntry", StringComparison.Ordinal))
            {
                var decoded = AnsRules.ChoiceAnsRules_RequestEntry.ResultDecoder!(exercised.ExerciseResult);
                return new ExerciseOutcome<AnsRules_RequestEntryResult>.One(decoded);
            }
        }

        throw new InvalidOperationException(
            $"Submission succeeded but no 'AnsRules_RequestEntry' exercise on contract '{contractId}' was recorded on transaction {tx.UpdateId}. " +
            "This is most often caused by the ILedgerClient implementation not populating TransactionResult.ExercisedEvents — " +
            "your ILedgerClient implementation must project the transaction's exercised events into TransactionResult.ExercisedEvents. " +
            "If your implementation does populate ExercisedEvents, ensure the participant is configured to return " +
            "LedgerEffects with verbose events so the exercise event survives projection.");
    }
}
