// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Contracts;
using Daml.Runtime.Data;

namespace Splice.Amulet.Name.Service;

public sealed partial record AnsRules
{
    /// <summary>
    /// Choice argument type for AnsRules_CollectInitialEntryPayment.
    /// </summary>
    public sealed record AnsRules_CollectInitialEntryPayment([property: DamlFieldAttribute("user")] Party User, [property: DamlFieldAttribute("entryContext")] ContractId<AnsEntryContext> EntryContext, [property: DamlFieldAttribute("paymentCid")] ContractId<Splice.Wallet.Payments.SubscriptionInitialPayment> PaymentCid, [property: DamlFieldAttribute("transferContext")] Splice.Amulet.AppTransferContext TransferContext) : IDamlRecord
    {
        /// <summary>Converts this value to a DamlRecord.</summary>
        public DamlRecord ToRecord() => DamlRecord.Create(
            DamlField.Create("user", User.ToDamlValue()),
            DamlField.Create("entryContext", EntryContext.ToDamlValue()),
            DamlField.Create("paymentCid", PaymentCid.ToDamlValue()),
            DamlField.Create("transferContext", TransferContext.ToRecord())
        );

        /// <summary>Creates an instance from a DamlRecord.</summary>
        public static AnsRules_CollectInitialEntryPayment FromRecord(DamlRecord record) => new AnsRules_CollectInitialEntryPayment(
            User: Party.FromDamlValue(record.GetRequiredField("user").As<DamlParty>()),
            EntryContext: new ContractId<AnsEntryContext>(record.GetRequiredField("entryContext").As<DamlContractId>().Value),
            PaymentCid: new ContractId<Splice.Wallet.Payments.SubscriptionInitialPayment>(record.GetRequiredField("paymentCid").As<DamlContractId>().Value),
            TransferContext: Splice.Amulet.AppTransferContext.FromRecord(record.GetRequiredField("transferContext").As<DamlRecord>())
        );

    }
}
