// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;

namespace Splice.Amulet.Name.Service;

/// <summary>
/// Generated from Daml record ExpectedPayment
/// </summary>
public sealed record ExpectedPayment([property: DamlFieldAttribute("dso")] Party Dso, [property: DamlFieldAttribute("sender")] Party Sender) : IDamlRecord
{
    /// <summary>Converts this value to a DamlRecord.</summary>
    public DamlRecord ToRecord() => DamlRecord.Create(
        DamlField.Create("dso", Dso.ToDamlValue()),
        DamlField.Create("sender", Sender.ToDamlValue())
    );

    /// <summary>Creates an instance from a DamlRecord.</summary>
    public static ExpectedPayment FromRecord(DamlRecord record) => new ExpectedPayment(
        Dso: Party.FromDamlValue(record.GetRequiredField("dso").As<DamlParty>()),
        Sender: Party.FromDamlValue(record.GetRequiredField("sender").As<DamlParty>())
    );

}
