// <auto-generated>
// This code was generated by daml-codegen-csharp.
// Do not edit this file manually.
// </auto-generated>

#nullable enable

using Daml.Runtime.Data;
using System;

namespace Splice.Api.Token.AllocationV2;

/// <summary>
/// Generated from Daml enum TransferSide
/// </summary>
public enum TransferSide
{
    /// <summary>SenderSide enum constructor.</summary>
    SenderSide,
    /// <summary>ReceiverSide enum constructor.</summary>
    ReceiverSide,
}

/// <summary>
/// Extension methods for TransferSide serialization.
/// </summary>
public static class TransferSideExtensions
{
    /// <summary>Converts to a DamlEnum value.</summary>
    public static DamlEnum ToDamlEnum(this TransferSide value)
    {
        return value switch
        {
            TransferSide.SenderSide => DamlEnum.Create("SenderSide"),
            TransferSide.ReceiverSide => DamlEnum.Create("ReceiverSide"),
            _ => throw new ArgumentOutOfRangeException(nameof(value), value, null)
        };
    }

    /// <summary>Creates an instance from a DamlEnum value.</summary>
    public static TransferSide FromDamlEnum(DamlEnum value)
    {
        return value.Constructor switch
        {
            "SenderSide" => TransferSide.SenderSide,
            "ReceiverSide" => TransferSide.ReceiverSide,
            _ => throw new ArgumentOutOfRangeException(nameof(value), value.Constructor, null)
        };
    }

    /// <summary>Decodes a Daml-LF JSON enum constructor directly into a DamlEnum, without going through reflection.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public static DamlEnum __ReadDamlLfJson(global::System.Text.Json.JsonElement json, global::Daml.Runtime.Serialization.DamlLfJsonDecodeContext context) =>
        global::Daml.Runtime.Serialization.DamlLfJsonDecoders.ReadEnumConstructor(json, context, ExpectedConstructors);

    private static readonly string[] ExpectedConstructors = ["SenderSide", "ReceiverSide"];

}
