name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  csharp-ci:
    uses: peacefulstudio/github-actions/.github/workflows/csharp-ci.yaml@v2
    with:
      dotnet-version: '10.0.x'
      build-matrix: '[{"name":"ubuntu-latest","runner":"ubuntu-latest","coverage":false}]'

  jvm-helper-ci:
    uses: peacefulstudio/github-actions/.github/workflows/scala-ci.yaml@v2
    with:
      working-directory: jvm-helper
